/**
 * BJJ glyph set — the single source of truth for NoGiMind's custom icons.
 *
 * Only `paths` (SVG `d` strings) and `circles` are declared here, so the same
 * geometry feeds both the React component (`BjjIcon.tsx`) and the standalone
 * SVG sprite used by the PWA / share previews
 * (`public/icons/bjj-sprite.svg`, regenerated by `npm run gen:bjj-sprite`).
 *
 * Drawing rules (kept in sync with lucide so both can sit next to each other):
 *   · 24×24 grid, ~2px safe area
 *   · stroke only — no fills, no gradients
 *   · stroke-width 2, round caps + joins, inherits `currentColor`
 *
 * The shapes are deliberately geometric and limb-abstract: they stay legible at
 * 16–20px, and each icon ships with a text label everywhere it is used.
 */

export type BjjIconName =
  | 'guard'
  | 'hook'
  | 'grip'
  | 'choke'
  | 'legLock'
  | 'mount'
  | 'escape'
  | 'takedown'
  | 'backTake'
  | 'chain'
  | 'tap'
  | 'frame'
  | 'brand'

export type BjjCircle = [cx: number, cy: number, r: number]

export type BjjGlyph = {
  /** Short human label — also the sprite `<title>`. */
  label: string
  /** SVG `d` strings. */
  paths?: string[]
  /** Circle geometry: [cx, cy, r]. */
  circles?: BjjCircle[]
  /** Optional stroke width override (defaults to 2). */
  strokeWidth?: number
}

export const BJJ_GLYPHS: Record<BjjIconName, BjjGlyph> = {
  /* ── Positions ─────────────────────────────────────────────────────────── */
  guard: {
    label: 'Guard',
    circles: [
      [5, 15.8, 1.8],
      [12.2, 6.6, 1.8],
    ],
    paths: ['M3.2 18.8h7.6', 'M12.2 18.6V9.4', 'M10.4 19.2c4.4 1 7-1 6.8-4.6'],
  },
  mount: {
    label: 'Ghim & Mount',
    circles: [[12, 8.4, 1.8]],
    paths: ['M3.4 18.6h17.2', 'M12 18.4V11.2', 'M7.6 12.6a4.4 4.4 0 0 1 8.8 0'],
  },
  backTake: {
    label: 'Back take',
    circles: [[11.4, 8, 1.9]],
    paths: [
      'M11.4 10v6',
      'M8.6 20.6c0-2.8 1.2-4.6 2.8-4.6s2.8 1.8 2.8 4.6',
      'M15.6 8.2a5.6 5.6 0 0 1 3.2 5.2',
      'M18.8 13.4l-2.2.6.5-2.3',
    ],
  },

  /* ── Attacks ───────────────────────────────────────────────────────────── */
  hook: {
    label: 'Hook / móc chân',
    circles: [[19.2, 15.4, 1.7]],
    paths: ['M8 4.6v8.6a4.4 4.4 0 0 0 8.4 1.6', 'M6.6 4.6h2.8'],
  },
  grip: {
    label: 'Grip / khoá tay',
    paths: [
      'M9.4 8.2a3.4 3.4 0 0 0 0 6.8',
      'M14.6 8.2a3.4 3.4 0 0 1 0 6.8',
      'M12 5.6v12.8',
    ],
  },
  choke: {
    label: 'Siết cổ',
    circles: [[9, 3, 1.5]],
    paths: ['M9 4.5v15', 'M5.6 9.6l12.8 6'],
  },
  legLock: {
    label: 'Leg lock / đường gối',
    circles: [[11.6, 11, 1.7]],
    paths: ['M6 5.4l5.6 5.6', 'M11.6 11.6v5.8a3.2 3.2 0 0 0 6.4 0', 'M13 9.6l4.4-2.2'],
  },
  chain: {
    label: 'Chuỗi submission',
    circles: [
      [8.2, 15.8, 2.6],
      [15.8, 8.2, 2.6],
    ],
    paths: ['M10 14l4-4'],
  },

  /* ── Defensive ─────────────────────────────────────────────────────────── */
  escape: {
    label: 'Thoát hiểm (bridge)',
    paths: ['M3.6 17.6c2.8-4.6 13.6-4.6 16.4 0', 'M12.4 12.4V7', 'M9.4 9.8l3-2.8 3 2.8'],
  },
  frame: {
    label: 'Khung chặn (frame)',
    paths: [
      'M6 19.4 9 13.6',
      'M18 19.4 15 13.6',
      'M9 13.6h6',
      'M12 13.6V6.6',
      'M9.6 8.8 12 6.4l2.4 2.4',
    ],
  },
  takedown: {
    label: 'Vật & takedown',
    circles: [[15.6, 7.4, 1.7]],
    paths: ['M14.6 9l-3.4 5.4', 'M11.2 14.4 7.4 18', 'M4.6 19.4h14.8'],
  },
  tap: {
    label: 'An toàn & tap',
    paths: [
      'M5.6 13.6V9.2a1.4 1.4 0 0 1 2.8 0v3.4',
      'M8.4 12.6V7.6a1.4 1.4 0 0 1 2.8 0v5',
      'M11.2 12.6V8.8a1.4 1.4 0 0 1 2.8 0v5.4',
      'M14 14.4v-2a1.4 1.4 0 0 1 2.8 0v3.4a5 5 0 0 1-5 5h-1.6a5 5 0 0 1-5-5v-2.2',
    ],
  },

  /* ── Brand ─────────────────────────────────────────────────────────────── */
  brand: {
    label: 'NoGiMind',
    paths: [
      'M8.4 3.8h7.2a4.6 4.6 0 0 1 4.6 4.6v7.2a4.6 4.6 0 0 1-4.6 4.6H8.4a4.6 4.6 0 0 1-4.6-4.6V8.4a4.6 4.6 0 0 1 4.6-4.6z',
      'M8.6 16.2V7.8l6.8 8.4V7.8',
    ],
  },
}

/** All names in a stable order (used by docs pages and the sprite build). */
export const BJJ_ICON_NAMES = Object.keys(BJJ_GLYPHS) as BjjIconName[]
