/**
 * BJJ glyph set — the single source of truth for NoGiMind's custom icons.
 *
 * Only `paths` (SVG `d` strings) and `circles` are declared here, so the same
 * geometry feeds both the React component (`BjjIcon.tsx`) and the standalone
 * SVG sprite used by the PWA / share previews
 * (`public/icons/bjj-sprite.svg`, regenerated by `npm run gen:bjj-sprite`).
 *
 * ── Drawing rules (enforced by `bjjIcons.test.tsx`) ───────────────────────
 *   · 24×24 grid, all ink inside 2–22 (safe area)
 *   · stroke only — no fills, no gradients; width 2 (2.4 for the brand mark),
 *     round caps + joins
 *   · **lines and cubic curves only** — no elliptical arcs, so the shape is
 *     unambiguous to read and to rasterise
 *   · **at least 2.5 units (≈1.7px at 16px) between strokes that are not
 *     supposed to touch**, otherwise two limbs merge into one blob
 *   · no gap narrower than one rendered pixel at 16px, or it disappears
 *   · heads are circles with r ≥ 2; nothing shorter than 3 units survives
 *   · **axis-aligned strokes sit on the 16px pixel grid**: a 2-unit stroke is
 *     1.33px wide, so a centre at an odd multiple of 0.75 lands as one crisp
 *     pixel and a centre at a multiple of 1.5 lands as two. Anything between
 *     (e.g. y = 19) spills into a half-covered neighbour and the line looks
 *     blurred — that is why mat lines use 18.75 and limbs use x.25/x.75.
 *
 * Every glyph is deliberately sparse: 2–4 elements, sized so the silhouette
 * still reads in a 16px nav item — the size the sidebar actually renders
 * (`h-4 w-4`).
 */

export type BjjIconName =
  | 'guard'
  | 'hook'
  | 'grip'
  | 'choke'
  | 'legLock'
  | 'mount'
  | 'escape'
  | 'takedown'
  | 'backTake'
  | 'chain'
  | 'tap'
  | 'frame'
  | 'brand'

export type BjjCircle = [cx: number, cy: number, r: number]

export type BjjGlyph = {
  /** Short human label — also the sprite `<title>`. */
  label: string
  /** SVG `d` strings. Lines (`M`/`L`/`H`/`V`) and cubics (`C`) only. */
  paths?: string[]
  /** Circle geometry: [cx, cy, r]. */
  circles?: BjjCircle[]
  /** Optional stroke width override (defaults to 2). */
  strokeWidth?: number
}

export const BJJ_GLYPHS: Record<BjjIconName, BjjGlyph> = {
  /* ── Positions ─────────────────────────────────────────────────────────── */
  guard: {
    label: 'Guard',
    circles: [[12, 6.4, 2.8]],
    paths: [
      'M3 18.75h10.5', // opponent's body on the mat
      'M12 8.8v9.95', // attacker standing inside the guard
      'M11 18.75C14.5 16.25 18.5 15 18.5 10.75', // the leg looping over the back
    ],
  },
  mount: {
    label: 'Ghim & Mount',
    circles: [[12, 6.6, 2.8]],
    paths: [
      'M2.5 18.75h19', // mat line
      'M12 9.2v4.3', // torso
      'M8 13.5h8', // hips sitting on the opponent
    ],
  },
  backTake: {
    label: 'Back take',
    circles: [[11, 7.8, 2.8]],
    paths: [
      'M11 10.4v4.6', // torso, joined to the hips so the figure does not float
      'M8 20C8.2 17.2 9.3 15 11 15C12.7 15 13.8 17.2 14 20', // seated legs
      // the arrow starts clear of the head (else the two merge at 16px)
      'M17.6 6.2C20.8 9.2 20.8 14 18.6 15.6M18.6 15.6l-2.4-1.2M18.6 15.6l-0.9-2.6',
    ],
  },

  /* ── Attacks ───────────────────────────────────────────────────────────── */
  hook: {
    label: 'Hook / móc chân',
    paths: [
      'M11.25 8.25h8.75', // the limb being hooked
      'M6.75 4.5v8.5C6.75 15.8 8.6 17.25 11.25 17.25', // hook curling underneath
    ],
  },
  grip: {
    label: 'Grip / khoá tay',
    paths: [
      'M8 3h8', // the forearm being gripped
      'M6.75 8.5v5C6.75 15.5 8.25 17 9.75 17', // left hand
      'M17.25 8.5v5C17.25 15.5 15.75 17 14.25 17', // right hand
    ],
  },
  choke: {
    label: 'Siết cổ',
    circles: [[9.75, 4.8, 2.8]],
    paths: [
      'M9.75 7.2v11.55', // neck
      'M15.6 8.4C18.6 10.2 19 14 15.8 16.6', // forearm wrapping around, clear of the head
    ],
  },
  legLock: {
    label: 'Leg lock / đường gối',
    paths: [
      'M5.25 5.25v6.75h5.25', // bent leg, knee at the corner
      // the grip is a bracket, not a shallow arc: shallow diagonals break up
      // into dashes once they are rasterised to a 16px bitmap
      'M13.25 8.25h2.5C17.35 8.25 18.4 10 18.4 12C18.4 14 17.35 15.75 16 15.75h-2.5',
    ],
  },
  chain: {
    label: 'Chuỗi submission',
    circles: [
      [8, 16, 3.2],
      [16, 8, 3.2],
    ],
    paths: ['M10.6 13.4L13.4 10.6'], // the link between them
  },

  /* ── Defensive ─────────────────────────────────────────────────────────── */
  escape: {
    label: 'Thoát hiểm (bridge)',
    paths: [
      'M3.5 18.75C6.5 12.75 17.5 12.75 20.5 18.75', // the bridge
      // shaft + head are one element, and the shaft stops short of the bridge
      'M12 10.25V6.6M9.4 9.2L12 6.6L14.6 9.2',
    ],
  },
  frame: {
    label: 'Khung chặn (frame)',
    paths: [
      'M5 20L12 12.5L19 20', // both forearms, bracing
      'M6.5 9C9 7.4 15 7.4 17.5 9', // the body being held off
    ],
  },
  takedown: {
    label: 'Vật & takedown',
    circles: [[15.5, 6.4, 2.8]],
    paths: [
      'M15.2 8.8L11.5 12.5', // torso falling
      'M11.5 12.5L9.5 18.75', // leg, landing on the mat
      'M3 18.75h18', // mat line
    ],
  },
  tap: {
    label: 'An toàn & tap',
    paths: [
      'M6.75 13V9',
      'M11.25 13V8.5',
      'M15.75 13V9.5',
      'M5.45 13.5C5.45 17.25 7.75 18.75 11.25 18.75C14.75 18.75 17.05 17.25 17.05 13.5', // palm
    ],
  },

  /* ── Brand ─────────────────────────────────────────────────────────────── */
  /**
   * The mark is a bare N, not a framed monogram: at 16px the frame's rounded
   * corners fall below 50% pixel coverage (the outline came apart into four
   * sides) and the monogram's counters closed up inside it. A wider, slightly
   * heavier letter keeps zero half-covered pixels and stays one solid shape.
   */
  brand: {
    label: 'NoGiMind',
    strokeWidth: 2.4,
    paths: ['M7.4 17.2V6.8l9.2 10.4V6.8'],
  },
}

/** All names in a stable order (used by docs pages and the sprite build). */
export const BJJ_ICON_NAMES = Object.keys(BJJ_GLYPHS) as BjjIconName[]
