import { lazy } from 'react'

export const DashboardPage = lazy(() => import('../pages/DashboardPage'))
export const LearnPage = lazy(() => import('../pages/LearnPage'))
export const SkillMapPage = lazy(() => import('../pages/SkillMapPage'))
export const SkillDetailPage = lazy(() => import('../pages/SkillDetailPage'))
export const MicroDetailsPage = lazy(() => import('../pages/MicroDetailsPage'))
export const TechniqueChainsPage = lazy(() => import('../pages/TechniqueChainsPage'))
export const SubmissionTroubleshootersPage = lazy(() => import('../pages/SubmissionTroubleshootersPage'))
export const SubmissionTroubleshooterDetailPage = lazy(() => import('../pages/SubmissionTroubleshooterDetailPage'))
export const EscapeMapsPage = lazy(() => import('../pages/EscapeMapsPage'))
export const EscapeMapDetailPage = lazy(() => import('../pages/EscapeMapDetailPage'))
export const ConceptsPage = lazy(() => import('../pages/ConceptsPage'))
export const ConceptDetailPage = lazy(() => import('../pages/ConceptDetailPage'))
export const PositionsPage = lazy(() => import('../pages/PositionsPage'))
export const PositionDetailPage = lazy(() => import('../pages/PositionDetailPage'))
export const DefensePage = lazy(() => import('../pages/DefensePage'))
export const DefenseDetailPage = lazy(() => import('../pages/DefenseDetailPage'))
export const ArchetypesPage = lazy(() => import('../pages/ArchetypesPage'))
export const ArchetypeDetailPage = lazy(() => import('../pages/ArchetypeDetailPage'))
export const GameTreePage = lazy(() => import('../pages/GameTreePage'))
export const MasteryMapPage = lazy(() => import('../pages/MasteryMapPage'))
export const GlossaryPage = lazy(() => import('../pages/GlossaryPage'))
export const AboutPage = lazy(() => import('../pages/AboutPage'))
export const SettingsPage = lazy(() => import('../pages/SettingsPage'))
export const SearchPage = lazy(() => import('../pages/SearchPage'))
export const SharedKnowledgePage = lazy(() => import('../pages/SharedKnowledgePage'))
export const NotFoundPage = lazy(() => import('../pages/NotFoundPage'))
