/**
 * A skill detail as generated by the build pipeline.
 * This is a flat merge of SkillMetaJson + SkillContentJson + locale,
 * matching the Zod-generated artifact exactly.
 */

export interface FeatureFlags {
  hasMicroDetails: boolean
  hasChecklist: boolean
  hasVideos: boolean
  hasStateMachine: boolean
}

export interface SkillDetail {
  id: string
  domain: string
  level: string
  locale: string
  name: string
  description: string
  summary?: string
  tags: string[]
  aliases: string[]
  keywords: string[]
  status: string
  version?: number
  updatedAt?: string
  searchBoost: number

  // Content sections
  shortInstruction?: string
  nextStep?: string
  whyItWorks: string[]
  systemLogic?: {
    corePrinciple: string
    decisionTree: Array<{ condition: string; action: string }>
    exitStrategies: string[]
  } | string[]
  keyCorrections: string[]
  moneyDetails: string[]
  coachingCues: string[]
  commonMistakes: string[]
  fixItFast: string[]
  safetySummary: string[]

  // Feature flags
  featureFlags: FeatureFlags

  // Content references
  contentRefs: {
    videos: string
    qualityChecklist: string
  }

  // Skill relationships
  prerequisiteSkillIds: string[]
  nextSkillIds: string[]
  relatedSkillIds: string[]
  relatedSkills: Array<{ id: string; name: string }>
  relatedPositionIds: string[]
  relatedPositions: Array<{ id: string; name: string }>
  relatedConceptIds: string[]
  relatedConcepts: Array<{ id: string; name: string }>
  archetypeIds: string[]
  relatedArchetypeIds: string[]
  trainingMethodIds: string[]
}

const generatedSkillsUrl = (locale: string, id: string): string =>
  `/generated/skills/${locale}/${id}.json`

const skillDetailCache = new Map<string, SkillDetail>()

/**
 * Load the full detail for a skill from the generated JSON artifact.
 * Falls back to the legacy data pipeline if the generated file is not found.
 */
export async function getSkillDetail(
  locale: string,
  id: string,
  options?: { useLegacy?: () => SkillDetail | null }
): Promise<SkillDetail | null> {
  const cacheKey = `${locale}:${id}`

  // Check cache
  const cached = skillDetailCache.get(cacheKey)
  if (cached) return cached

  try {
    const response = await fetch(generatedSkillsUrl(locale, id))
    if (!response.ok) throw new Error(`HTTP ${response.status}`)
    const detail: SkillDetail = await response.json()

    // Only cache in production — in dev we want HMR to work
    if (import.meta.env.PROD) {
      skillDetailCache.set(cacheKey, detail)
    }

    return detail
  } catch {
    // Fallback to legacy pipeline
    if (options?.useLegacy) {
      const legacy = options.useLegacy()
      if (legacy) {
        skillDetailCache.set(cacheKey, legacy)
        return legacy
      }
    }
    return null
  }
}

/**
 * Prefetch a skill detail into cache.
 */
export function prefetchSkillDetail(locale: string, id: string): void {
  const cacheKey = `${locale}:${id}`
  if (!skillDetailCache.has(cacheKey)) {
    getSkillDetail(locale, id).catch(() => { /* silent fetch */ })
  }
}

/**
 * Clear the skill detail cache.
 */
export function clearSkillDetailCache(): void {
  skillDetailCache.clear()
}
