#!/usr/bin/env python3
"""Insert microDetailSystem and qualityChecklist entries for 9 new skills."""

import re

# Read the current files
with open('src/data/microDetailSystems.ts', 'r') as f:
    micro_content = f.read()

with open('src/data/qualityChecklists.ts', 'r') as f:
    checklist_content = f.read()

# --- microDetailSystems entries ---
micro_entries = """
  'closed-guard-posture-control': {
    overview: lt('Kiểm soát posture bằng leg tension, hip angle và hand fight để mở sweep và submission.', 'Control posture with leg tension, hip angle, and hand fighting to open sweeps and submissions.', 'Contrôler posture avec tension jambes, angle hanche et hand fighting pour ouvrir sweeps et soumissions.'),
    topFiveDetails: [
      md('cgpc-leg-tension', 'angle', lt('Chân khóa hông', 'Legs lock hips', 'Jambes verrouillent hanches'), lt('Hai chân khóa sát lưng họ và ép hông xuống.', 'Lock legs tight across their back and press hips down.', 'Verrouiller jambes dos et presser hanches bas.'), 'both', 'close_in', ['legs', 'hips', 'knees'], lt('Khi họ bắt đầu posture.', 'When they start to posture up.', 'Quand ils commencent à se redresser.'), lt('Leg lock giữ họ thấp và không xoay được.', 'Leg lock keeps them low and unable to turn.', 'Leg lock garde bas et sans rotation.'), lt('Chân lỏng để họ thoát.', 'Loose legs let them escape.', 'Jambes lâches pour sortie.'), lt('Squeeze then break.', 'Squeeze then break.', 'Serrez puis cassez.'), lt('Họ không thể posture lên.', 'They cannot posture up.', 'Ils ne peuvent pas redresser.'), safetyText),
      md('cgpc-hip-angle', 'angle', lt('Hông lệch side', 'Hip angle shift', 'Décalage angle hanche'), lt('Xoay hông ra ngoài một bên để phá centerline của họ.', 'Shift hips to one side to break their centerline.', 'Décaler hanches pour briser centerline.'), 'far', 'rotate_right', ['hips', 'pelvis', 'feet'], lt('Khi bạn chuẩn bị sweep.', 'When you prepare to sweep.', 'Quand vous préparez sweep.'), lt('Hip angle mở đường sweep và submission.', 'Hip angle opens sweep and submission paths.', 'Angle hanche ouvre sweep et soumission.'), lt('Nằm thẳng dưới họ.', 'Staying flat under them.', 'Rester plat.'), lt('Angle then attack.', 'Angle then attack.', 'Angle puis attaque.'), lt('Bạn có góc để sweep.', 'You have angle to sweep.', 'Angle pour sweep.'), safetyText),
      md('cgpc-hand-fight', 'hand', lt('Thắng hand fight', 'Win the hand fight', 'Gagner hand fight'), lt('Tay trên kiểm soát elbow, tay dưới giữ tay đối thủ.', 'Top hand controls elbow, bottom hand grips their hand.', 'Main haute contrôle coude, main basse grip main.'), 'both', undefined, ['hands', 'wrists', 'arms'], lt('Khi họ che neck line.', 'When they cover the neck line.', 'Quand ils couvrent ligne cou.'), lt('Hand fight phá cấu trúc phòng thủ.', 'Hand fight breaks defensive structure.', 'Hand fight brise structure défense.'), lt('Bỏ hand fight.', 'Dropping the hand fight.', 'Lâcher hand fight.'), lt('Win hands then posture.', 'Win hands then posture.', 'Gagnez mains puis posture.'), lt('Tay họ bị khóa.', 'Their hands are trapped.', 'Mains piégées.'), safetyText),
      md('cgpc-elbow-control', 'elbow', lt('Kéo elbow khỏi ribs', 'Pull elbow from ribs', 'Tirer coude des côtes'), lt('Kéo khuỷu họ ra khỏi sườn bằng tay trên.', 'Pull their elbow away from the ribs with the top hand.', 'Tirer leur coude des côtes avec main haute.'), 'near', 'pull_toward_you', ['elbows', 'arms', 'ribs'], lt('Sau khi hand fight thắng.', 'After winning the hand fight.', 'Après hand fight gagné.'), lt('Elbow xa ribs = sweep entry mở.', 'Elbow away from ribs opens sweep entry.', 'Coude loin côtes = entrée sweep ouverte.'), lt('Kéo mù không target.', 'Pulling without a target.', 'Tirer sans cible.'), lt('Elbow then hip bump.', 'Elbow then hip bump.', 'Coude puis hip bump.'), lt('Elbow đã tách khỏi body.', 'Elbow is separated from the body.', 'Coude écarté du corps.'), safetyText),
      md('cgpc-head-control', 'head', lt('Kiểm soát đầu', 'Head control', 'Contrôle tête'), lt('Một tay sau đầu họ kéo xuống, tay kia giữ elbow.', 'One hand behind their head pulls down, the other holds the elbow.', 'Une main derrière tête tire bas, autre tient coude.'), 'near', 'pin_in', ['head', 'neck', 'hands'], lt('Khi bạn giữ posture xuống.', 'When you keep their posture down.', 'Quand vous gardez posture basse.'), lt('Head control ngăn posture rebuild.', 'Head control prevents posture rebuild.', 'Contrôle tête empêche reconstruction posture.'), lt('Để họ ngóc đầu.', 'Letting them lift the head.', 'Laisser relever tête.'), lt('Head down, elbow out.', 'Head down, elbow out.', 'Tête bas, coude dehors.'), lt('Posture họ đã chết.', 'Their posture is dead.', 'Posture morte.'), safetyText),
    ],
    leftRightGuides: [
      guide('cgpc-right', lt('Khi bạn posture phải.', 'When you posture to the right.', 'Quand vous postez à droite.'), lt('Tay trái sau đầu.', 'Left hand behind head.', 'Main gauche derrière tête.'), lt('Tay phải kéo elbow.', 'Right hand pulls elbow.', 'Main droite tire coude.'), lt('Chân trái lên hông.', 'Left leg to hip.', 'Jambe gauche hanche.'), lt('Chân phải khóa lưng.', 'Right leg locks back.', 'Jambe droite verrouille dos.'), lt('Đầu sát ngực họ.', 'Head close to their chest.', 'Tête près poitrine.'), lt('Hông xoay trái.', 'Hips rotate left.', 'Hanches tournent gauche.'), lt('Legs squeeze, hands break.', 'Legs squeeze, hands break.', 'Jambes serrent, mains cassent.')),
      guide('cgpc-left', lt('Khi bạn posture trái.', 'When you posture to the left.', 'Quand vous postez à gauche.'), lt('Tay phải sau đầu.', 'Right hand behind head.', 'Main droite derrière tête.'), lt('Tay trái kéo elbow.', 'Left hand pulls elbow.', 'Main gauche tire coude.'), lt('Chân phải lên hông.', 'Right leg to hip.', 'Jambe droite hanche.'), lt('Chân trái khóa lưng.', 'Left leg locks back.', 'Jambe gauche verrouille dos.'), lt('Đầu sát ngực.', 'Head close to chest.', 'Tête près poitrine.'), lt('Hông xoay phải.', 'Hips rotate right.', 'Hanches tournent droite.'), lt('Posture first, then sweep.', 'Posture first, then sweep.', 'Posture d\\'abord, puis sweep.')),
    ],
    fastFinishPaths: [
      path('cgpc-fast-sweep', lt('Đường sweep nhanh', 'Fast sweep path', 'Chemin sweep rapide'), [
        { id: '1', order: 1, instruction: lt('Leg lock tight.', 'Leg lock tight.', 'Leg lock serré.'), keyBodyPart: 'legs', commonMistake: lt('Chân lỏng.', 'Loose legs.', 'Jambes lâches.') },
        { id: '2', order: 2, instruction: lt('Pull elbow out.', 'Pull elbow out.', 'Tirez coude dehors.'), keyBodyPart: 'elbows', commonMistake: lt('Kéo không đúng tay.', 'Pulling wrong arm.', 'Tirer mauvais bras.') },
        { id: '3', order: 3, instruction: lt('Angle hips and hip bump.', 'Angle hips and hip bump.', 'Angle hanche et hip bump.'), keyBodyPart: 'hips', commonMistake: lt('Nằm phẳng.', 'Staying flat.', 'Rester plat.') },
        { id: '4', order: 4, instruction: lt('Follow vào mount/side.', 'Follow into mount/side.', 'Suivi mount/side.'), keyBodyPart: 'hips', commonMistake: lt('Không follow.', 'Not following.', 'Pas suivi.') },
      ], lt('Elbow xa ribs và head down.', 'Elbow away and head down.', 'Coude loin et tête bas.'), lt('Họ rebuild posture và base.', 'They rebuild posture and base.', 'Ils reconstruisent posture et base.'), lt('Chuyển pull guard hoặc sweep khác.', 'Switch to pull guard or another sweep.', 'Changer pull guard ou autre sweep.'), safetyText),
    ],
    troubleshootingTips: [
      { problem: lt('Không phá được posture.', 'Cannot break posture.', 'Peut pas casser posture.'), quickFix: lt('Squeeze legs, kéo head.', 'Squeeze legs, pull head.', 'Serrez jambes, tirez tête.'), cue: lt('Legs first.') },
      { problem: lt('Họ base nặng.', 'Their base is heavy.', 'Base lourde.'), quickFix: lt('Đổi hip angle và kéo elbow.', 'Change hip angle and pull elbow.', 'Changez angle hanche et tirez coude.'), cue: lt('Angle then pull.') },
      { problem: lt('Tay họ chặn cổ.', 'Their hands block the neck.', 'Mains bloquent cou.'), quickFix: lt('Hand fight lại từ đầu.', 'Re-hand fight from the start.', 'Refaites hand fight.'), cue: lt('Win hands.') },
    ],
    doNotDo: la(
      ['Đừng để chân lỏng.', 'Đừng giữ tay họ quá lâu.', 'Đừng nằm phẳng.', 'Đừng bỏ head control.', 'Đừng sweep khi chưa có elbow out.'],
      ['Do not let legs go loose.', 'Do not hold their arms too long.', 'Do not stay flat.', 'Do not drop head control.', 'Do not sweep without elbow out.'],
      ['Jambes lâches.', 'Tenir bras trop long.', 'Rester plat.', 'Perdre contrôle tête.', 'Sweep sans coude dehors.'],
    ),
    safetyNotes: safety,
  },
  'closed-guard-sweeps': {
    overview: lt('Sweep từ closed guard bằng hip bump, scissor và flower sweep khi elbow đã tách và posture đã gãy.', 'Sweep from closed guard with hip bump, scissor, and flower sweeps when the elbow is separated and posture is broken.', 'Sweep depuis closed guard avec hip bump, scissor et flower sweeps quand coude est écarté et posture cassée.'),
    topFiveDetails: [
      md('cgs-hip-bump', 'angle', lt('Hip bump swing', 'Hip bump swing', 'Hip bump swing'), lt('Nhấc hông swing người lên về phía vai họ.', 'Lift hips and swing your body toward their shoulder.', 'Soulever hanches et balancer vers épaule.'), 'both', 'drive_diagonal', ['hips', 'knees', 'shoulders'], lt('Khi họ ép người về trước.', 'When they press forward.', 'Quand ils pressent avant.'), lt('Hip bump dùng momentum họ để sweep.', 'Hip bump uses their momentum to sweep.', 'Hip bump utilise momentum pour sweep.'), lt('Hip bump yếu không đủ lực.', 'Weak hip bump with no power.', 'Hip bump faible.'), lt('Bump hard, angle wide.', 'Bump hard, angle wide.', 'Bump fort, angle large.'), lt('Họ mất base và post.', 'They lose base and post.', 'Perdent base et postent.'), safetyText),
      md('cgs-scissor', 'leg', lt('Scissor sweep footwork', 'Scissor sweep footwork', 'Footwork scissor sweep'), lt('Chân dưới cắt chân họ, chân trên kẹp chest và xoay.', 'Bottom leg cuts their leg, top leg traps chest and rotates.', 'Jambe bas coupe jambe, jambe haute piège poitrine et tourne.'), 'right', 'rotate_right', ['legs', 'knees', 'chest'], lt('Khi họ step 1 chân lên.', 'When they step one leg up.', 'Quand ils montent une jambe.'), lt('Scissor cắt base và xoay họ sang side.', 'Scissor cuts base and rotates them sideways.', 'Scissor coupe base et tourne côté.'), lt('Chân trên không kẹp chest.', 'Top leg not trapping chest.', 'Jambe haute pas piège poitrine.'), lt('Cut with bottom, trap with top.', 'Cut with bottom, trap with top.', 'Coupez bas, piégez haut.'), lt('Base bị cắt, họ nghiêng.', 'Base cut, they tilt.', 'Base coupée, ils basculent.'), safetyText),
      md('cgs-flower', 'angle', lt('Flower sweep pendulum', 'Flower sweep pendulum', 'Pendulum flower sweep'), lt('Đưa chân lên cao cùng bên và pendulum swing xuống.', 'Bring both legs high on one side and pendulum swing down.', 'Jambes hautes côté et pendulum swing bas.'), 'far', 'rotate_right', ['legs', 'hips', 'shoulders'], lt('Khi họ base rộng.', 'When they base wide.', 'Quand base large.'), lt('Flower sweep dùng pendulum lực hơn force.', 'Flower sweep uses pendulum not force.', 'Flower sweep utilise pas force.'), lt('Kéo tay thay vì swing chân.', 'Pulling arm instead of swinging legs.', 'Tirer bras au lieu swing jambes.'), lt('Swing then pull.', 'Swing then pull.', 'Swing puis tirez.'), lt('Họ bay qua.', 'They fly over.', 'Ils volent.'), safetyText),
      md('cgs-posture-break', 'head', lt('Phá posture trước sweep', 'Break posture before sweep', 'Casser posture avant sweep'), lt('Kéo head và elbow xuống trước khi sweep.', 'Pull head and elbow down before sweeping.', 'Tirer tête et coude bas avant sweep.'), 'near', 'pull_toward_you', ['head', 'hands', 'elbows'], lt('Trước mỗi sweep.', 'Before every sweep.', 'Avant chaque sweep.'), lt('Posture thấp = sweep dễ hơn.', 'Low posture = easier sweep.', 'Posture basse = sweep plus facile.'), lt('Sweep khi họ còn posture.', 'Sweeping while they still have posture.', 'Sweep avec posture encore haute.'), lt('Break first, sweep second.', 'Break first, sweep second.', 'Cassez d\\'abord, sweep ensuite.'), lt('Họ không thể post để chống.', 'They cannot post to defend.', 'Peuvent pas poster pour défendre.'), safetyText),
      md('cgs-follow', 'timing', lt('Follow lên top', 'Follow to top', 'Suivre vers top'), lt('Sau sweep, kéo người theo và lên mount hoặc side.', 'After sweep, pull yourself and come to mount or side.', 'Après sweep, vous hisser vers mount ou side.'), 'both', 'drive_forward', ['hips', 'feet', 'chest'], lt('Khi sweep hoàn tất.', 'When sweep is done.', 'Quand sweep fini.'), lt('Follow nhanh giữ vị trí top.', 'Fast follow keeps top position.', 'Suivi rapide garde top.'), lt('Để sweep trôi, họ recover.', 'Letting sweep slide, they recover.', 'Laisser sweep glisser, recovery.'), lt('Follow now, settle later.', 'Follow now, settle later.', 'Suivez maintenant, stabilisez après.'), lt('Bạn đã lên top.', 'You are on top.', 'Vous êtes top.'), safetyText),
    ],
    leftRightGuides: [
      guide('cgs-right', lt('Sweep sang phải.', 'Sweep to the right.', 'Sweep droite.'), lt('Tay trái kéo sleeve.', 'Left hand pulls sleeve.', 'Main gauche tire manche.'), lt('Tay phải kéo cổ.', 'Right hand pulls neck.', 'Main droite tire cou.'), lt('Chân trái làm scissor.', 'Left leg does scissor.', 'Jambe gauche fait scissor.'), lt('Chân phải kẹp chest.', 'Right leg traps chest.', 'Jambe droite piège poitrine.'), lt('Đầu sát vai họ.', 'Head close to shoulder.', 'Tête près épaule.'), lt('Hông swing theo sweep.', 'Hips swing with sweep.', 'Hanches swing avec sweep.'), lt('Break posture, then sweep.', 'Break posture, then sweep.', 'Cassez posture, puis sweep.')),
      guide('cgs-left', lt('Sweep sang trái.', 'Sweep to the left.', 'Sweep gauche.'), lt('Tay phải kéo sleeve.', 'Right hand pulls sleeve.', 'Main droite tire manche.'), lt('Tay trái kéo cổ.', 'Left hand pulls neck.', 'Main gauche tire cou.'), lt('Chân phải làm scissor.', 'Right leg does scissor.', 'Jambe droite fait scissor.'), lt('Chân trái kẹp chest.', 'Left leg traps chest.', 'Jambe gauche piège poitrine.'), lt('Đầu sát vai.', 'Head close to shoulder.', 'Tête près épaule.'), lt('Hông swing.', 'Hips swing.', 'Hanches swing.'), lt('Angle, follow, settle.', 'Angle, follow, settle.', 'Angle, suivi, stabilise.')),
    ],
    fastFinishPaths: [
      path('cgs-fast-path', lt('Đường sweep nhanh', 'Fast sweep path', 'Chemin sweep rapide'), [
        { id: '1', order: 1, instruction: lt('Phá posture.', 'Break posture.', 'Casser posture.'), keyBodyPart: 'head', commonMistake: lt('Không phá posture.', 'No posture break.', 'Pas cassure posture.') },
        { id: '2', order: 2, instruction: lt('Kéo elbow ra.', 'Pull elbow out.', 'Tirer coude dehors.'), keyBodyPart: 'elbows', commonMistake: lt('Kéo sai tay.', 'Wrong arm.', 'Mauvais bras.') },
        { id: '3', order: 3, instruction: lt('Chọn sweep và thực hiện.', 'Choose sweep and execute.', 'Choisir sweep et exécuter.'), keyBodyPart: 'hips', commonMistake: lt('Chần chừ.', 'Hesitation.', 'Hésitation.') },
        { id: '4', order: 4, instruction: lt('Follow lên top.', 'Follow to top.', 'Suivre vers top.'), keyBodyPart: 'hips', commonMistake: lt('Không follow.', 'No follow.', 'Pas suivi.') },
      ], lt('Elbow tách, posture thấp.', 'Elbow out, posture low.', 'Coude sorti, posture basse.'), lt('Họ base lại.', 'They re-base.', 'Ils rebasent.'), lt('Reset guard hoặc đổi sweep.', 'Reset guard or change sweep.', 'Reset garde ou changer sweep.'), safetyText),
    ],
    troubleshootingTips: [
      { problem: lt('Không lift được họ.', 'Cannot lift them.', 'Peut pas lever.'), quickFix: lt('Kéo head thấp hơn, swing hông.', 'Pull head lower, swing hips.', 'Tirez tête plus bas, swing hanches.'), cue: lt('Swing hard.') },
      { problem: lt('Sweep xong mất top.', 'Sweep done but lose top.', 'Sweep fait mais perd top.'), quickFix: lt('Follow nhanh và settle.', 'Follow fast and settle.', 'Suivez vite et stabilisez.'), cue: lt('Follow now.') },
      { problem: lt('Họ post chống sweep.', 'They post to block sweep.', 'Ils postent contre sweep.'), quickFix: lt('Đổi loại sweep hoặc reset.', 'Switch sweep type or reset.', 'Changez type sweep ou reset.'), cue: lt('Switch sweep.') },
    ],
    doNotDo: la(
      ['Đừng sweep khi chưa phá posture.', 'Đừng dùng tay kéo quá nhiều.', 'Đừng để sweep trôi.', 'Đừng giữ một sweep quá lâu.'],
      ['Do not sweep without breaking posture.', 'Do not pull too much with arms.', 'Do not let sweep slide.', 'Do not stay on one sweep too long.'],
      ['Pas sweep sans cassure posture.', 'Pas tirer trop aux bras.', 'Pas laisser sweep glisser.', 'Pas rester un sweep trop long.'],
    ),
    safetyNotes: safety,
  },
  'de-la-riva-sweeps': {
    overview: lt('Sweep từ DLR bằng hook inside, sleeve grip và hip rotation để vào X-guard, SLX hoặc lên top.', 'Sweep from DLR with inside hook, sleeve grip, and hip rotation to enter X-guard, SLX, or come on top.', 'Sweep depuis DLR avec hook intérieur, grip manche et rotation hanche pour X-guard, SLX ou top.'),
    topFiveDetails: [
      md('dlrs-hook', 'hook', lt('DLR hook kéo', 'DLR hook pulls', 'Hook DLR tire'), lt('Hook chân kéo về phía bạn và xoay hông họ.', 'Hook their leg toward you and rotate their hip.', 'Hooker leur jambe vers vous et tourner hanche.'), 'inside', 'pull_toward_you', ['feet', 'shins', 'hips'], lt('Khi bạn có sleeve grip.', 'When you have the sleeve grip.', 'Quand vous avez grip manche.'), lt('Hook kéo phá base họ.', 'Hook pull breaks their base.', 'Hook tir brise leur base.'), lt('Hook không tension.', 'Hook without tension.', 'Hook sans tension.'), lt('Hook active, sleeve pulls.', 'Hook active, sleeve pulls.', 'Hook actif, manche tire.'), lt('Họ mất base.', 'They lose base.', 'Ils perdent base.'), safetyText),
      md('dlrs-sleeve', 'grip', lt('Sleeve grip kéo xa', 'Sleeve grip pulls away', 'Grip manche tire loin'), lt('Grip và kéo sleeve đối thủ ra xa để họ không post.', 'Grip and pull their sleeve away so they cannot post.', 'Grip et tirer manche loin pour pas poster.'), 'far', 'pull_away', ['hands', 'wrists', 'arms'], lt('Khi hook đang kéo.', 'When the hook is pulling.', 'Quand hook tire.'), lt('Sleeve xa = họ không base được.', 'Sleeve away = no base possible.', 'Manche loin = pas base possible.'), lt('Buông sleeve.', 'Releasing sleeve.', 'Lâcher manche.'), lt('Hook và sleeve cùng kéo.', 'Hook and sleeve pull together.', 'Hook et manche tirent ensemble.'), lt('Post tay họ chết.', 'Their hand post is dead.', 'Post main mort.'), safetyText),
      md('dlrs-hip-rotation', 'angle', lt('Hip rotation entry', 'Hip rotation entry', 'Rotation hanche entrée'), lt('Xoay hông ra ngoài và đưa chân trong lên hip line.', 'Rotate hips outward and bring inside leg to hip line.', 'Tourner hanches dehors et jambe intérieure vers hip line.'), 'both', 'rotate_right', ['hips', 'knees', 'feet'], lt('Sau hook và sleeve connected.', 'After hook and sleeve are connected.', 'Après hook et manche connectés.'), lt('Hip rotation mở X-guard và SLX entry.', 'Hip rotation opens X-guard and SLX entries.', 'Rotation hanche ouvre X-guard et SLX.'), lt('Không xoay hông.', 'No hip rotation.', 'Pas rotation hanche.'), lt('Rotate và insert.', 'Rotate and insert.', 'Tournez et insérez.'), lt('Knee và hip line sạch.', 'Knee and hip line are clear.', 'Knee et hip line libres.'), safetyText),
      md('dlrs-x-entry', 'timing', lt('X-guard timing', 'X-guard timing', 'Timing X-guard'), lt('Khi họ step back, đưa chân qua và vào X-guard.', 'When they step back, bring your leg across into X-guard.', 'Quand ils reculent, jambe en travers vers X-guard.'), 'both', 'drive_forward', ['feet', 'legs', 'hips'], lt('Khi họ di chuyển ra sau.', 'When they move backward.', 'Quand ils reculent.'), lt('Timing đúng = transition mượt.', 'Correct timing = smooth transition.', 'Bon timing = transition douce.'), lt('Step quá sớm.', 'Stepping too early.', 'Step trop tôt.'), lt('Step on their step.', 'Step on their step.', 'Step sur leur step.'), lt('X-guard lock active.', 'X-guard lock active.', 'Lock X-guard actif.'), safetyText),
      md('dlrs-finish', 'finish', lt('Sweep finish', 'Sweep finish', 'Finish sweep'), lt('Kéo họ qua bằng hook và kết thúc ở side control hoặc mount.', 'Pull them over with the hook and finish in side control or mount.', 'Les tirer avec hook et finir en side control ou mount.'), 'both', 'drive_forward', ['hips', 'feet', 'chest'], lt('Khi họ mất base.', 'When they lose base.', 'Quand ils perdent base.'), lt('Finish nhanh ngăn họ recover.', 'Fast finish prevents recovery.', 'Finish rapide empêche recovery.'), lt('Sweep xong không follow.', 'Sweep without follow-up.', 'Sweep sans suivi.'), lt('Sweep then settle.', 'Sweep then settle.', 'Sweep puis stabilisez.'), lt('Bạn lên top.', 'You are on top.', 'Vous êtes top.'), safetyText),
    ],
    leftRightGuides: [
      guide('dlrs-right', lt('DLR sweep phải.', 'DLR sweep right.', 'Sweep DLR droite.'), lt('Tay trái kéo sleeve.', 'Left hand pulls sleeve.', 'Main gauche tire manche.'), lt('Tay phải giữ wrist.', 'Right hand holds wrist.', 'Main droite tient wrist.'), lt('Chân trái DLR hook.', 'Left leg DLR hook.', 'Jambe gauche hook DLR.'), lt('Chân phải post và xoay.', 'Right leg post and rotate.', 'Jambe droite post et tourne.'), lt('Đầu sát chest.', 'Head close to chest.', 'Tête près poitrine.'), lt('Hông xoay ra ngoài.', 'Hips rotate outward.', 'Hanches tournent dehors.'), lt('Hook then rotate.', 'Hook then rotate.', 'Hook puis rotation.')),
      guide('dlrs-left', lt('DLR sweep trái.', 'DLR sweep left.', 'Sweep DLR gauche.'), lt('Tay phải kéo sleeve.', 'Right hand pulls sleeve.', 'Main droite tire manche.'), lt('Tay trái giữ wrist.', 'Left hand holds wrist.', 'Main gauche tient wrist.'), lt('Chân phải DLR hook.', 'Right leg DLR hook.', 'Jambe droite hook DLR.'), lt('Chân trái rotate.', 'Left leg rotate.', 'Jambe gauche tourne.'), lt('Đầu sát chest họ.', 'Head close to their chest.', 'Tête près poitrine.'), lt('Hông xoay ngoài.', 'Hips turn outward.', 'Hanches tournent dehors.'), lt('Hook, sleeve, rotate.', 'Hook, sleeve, rotate.', 'Hook, manche, rotation.')),
    ],
    fastFinishPaths: [
      path('dlrs-fast-sweep', lt('Đường sweep nhanh', 'Fast sweep path', 'Chemin sweep rapide'), [
        { id: '1', order: 1, instruction: lt('Kích hoạt hook.', 'Activate the hook.', 'Activer le hook.'), keyBodyPart: 'feet', commonMistake: lt('Hook chết.', 'Dead hook.', 'Hook mort.') },
        { id: '2', order: 2, instruction: lt('Kéo sleeve xa.', 'Pull sleeve away.', 'Tirer manche loin.'), keyBodyPart: 'hands', commonMistake: lt('Buông sleeve.', 'Releasing sleeve.', 'Lâcher manche.') },
        { id: '3', order: 3, instruction: lt('Xoay hông vào entry.', 'Rotate hips into entry.', 'Tourner hanches entrée.'), keyBodyPart: 'hips', commonMistake: lt('Không rotation.', 'No rotation.', 'Pas rotation.') },
        { id: '4', order: 4, instruction: lt('Sweep và follow.', 'Sweep and follow.', 'Sweep et suivre.'), keyBodyPart: 'hips', commonMistake: lt('Không finish.', 'No finish.', 'Pas finish.') },
      ], lt('Hook active, sleeve xa.', 'Hook active, sleeve away.', 'Hook actif, manche loin.'), lt('Họ base lại.', 'They re-base.', 'Ils rebasent.'), lt('Reset DLR hoặc chuyển K-guard.', 'Reset DLR or switch to K-guard.', 'Reset DLR ou passer K-guard.'), safetyText),
    ],
    troubleshootingTips: [
      { problem: lt('Hook không kéo được.', 'Hook cannot pull.', 'Hook peut pas tirer.'), quickFix: lt('Kéo chân sâu hơn và tension.', 'Pull leg deeper and add tension.', 'Tirez jambe plus profond et tension.'), cue: lt('Hook tension.') },
      { problem: lt('Họ step back ra xa.', 'They step far back.', 'Ils reculent loin.'), quickFix: lt('Vào X-guard hoặc SLX ngay.', 'Enter X-guard or SLX immediately.', 'Entrez X-guard ou SLX immédiatement.'), cue: lt('X-guard now.') },
      { problem: lt('Không vào được entry.', 'Cannot enter the entry.', 'Peut pas entrer.'), quickFix: lt('Xoay hông thêm và kéo sleeve.', 'Rotate hips more and pull sleeve.', 'Tournez hanches plus et tirez manche.'), cue: lt('More rotation.') },
    ],
    doNotDo: la(
      ['Đừng để hook chết.', 'Đừng quên kéo sleeve.', 'Đừng ở DLR quá lâu.', 'Đừng xoay hông không timing.', 'Đừng sweep mà không follow.'],
      ['Do not let the hook go dead.', 'Do not forget to pull the sleeve.', 'Do not stay in DLR too long.', 'Do not rotate without timing.', 'Do not sweep without following.'],
      ['Hook mort.', 'Oublier manche.', 'Rester DLR trop long.', 'Rotation sans timing.', 'Sweep sans suivi.'],
    ),
    safetyNotes: safety,
  },
  'de-la-riva-back-take': {
    overview: lt('Back take từ DLR bằng far hip control, berimbolo spin và hook placement để kết thúc ở back control.', 'Back take from DLR with far hip control, berimbolo spin, and hook placement to finish in back control.', 'Prise de dos depuis DLR avec contrôle hanche loin, berimbolo et placement hook pour dos.'),
    topFiveDetails: [
      md('dlrbt-far-hip', 'grip', lt('Far hip grip', 'Far hip grip', 'Grip hanche loin'), lt('Một tay giữ far hip belt/pants trước khi spin.', 'One hand grips the far hip belt/pants before the spin.', 'Main grip ceinture/pantalon hanche loin avant spin.'), 'far', 'pin_in', ['hands', 'hips', 'belt'], lt('Khi họ chống sweep.', 'When they defend the sweep.', 'Quand ils défendent sweep.'), lt('Far hip grip kéo họ vào back line.', 'Far hip grip pulls them into back line.', 'Grip hanche loin tire vers ligne dos.'), lt('Bỏ far hip grip.', 'Releasing far hip grip.', 'Lâcher grip hanche loin.'), lt('Grip the far hip.', 'Grip the far hip.', 'Grip hanche loin.'), lt('Họ bị kéo vào back.', 'They are pulled into back.', 'Tirés vers dos.'), safetyText),
      md('dlrbt-spin', 'angle', lt('Berimbolo spin', 'Berimbolo spin', 'Spin berimbolo'), lt('Kéo far hip và xoay shoulders để đưa đầu xuống hông họ.', 'Pull far hip and rotate shoulders to bring your head to their hip.', 'Tirer hanche loin et tourner épaules pour tête vers leur hanche.'), 'both', 'rotate_left', ['shoulders', 'hips', 'head'], lt('Khi far hip grip active.', 'When far hip grip is active.', 'Quand grip hanche loin actif.'), lt('Spin đưa bạn vào back line.', 'Spin brings you to the back line.', 'Spin amène ligne dos.'), lt('Spin không có direction.', 'Spin without direction.', 'Spin sans direction.'), lt('Pull and rotate.', 'Pull and rotate.', 'Tirez et tournez.'), lt('Bạn ở back angle.', 'You are at back angle.', 'Vous angle dos.'), safetyText),
      md('dlrbt-hook', 'hook', lt('Hook placement', 'Hook placement', 'Placement hook'), lt('Trong khi spin, đưa chân trên vào hook line lưng họ.', 'During the spin, place the top leg into the back hook line.', 'Pendant spin, jambe haute vers ligne hook dos.'), 'inside', 'close_in', ['feet', 'legs', 'hips'], lt('Khi spin hoàn tất.', 'When spin is complete.', 'Quand spin fini.'), lt('Hook đúng = back control secure.', 'Correct hook = secure back control.', 'Bon hook = dos sécurisé.'), lt('Hook thấp quá.', 'Hook too low.', 'Hook trop bas.'), lt('Hook high, then seatbelt.', 'Hook high, then seatbelt.', 'Hook haut, puis seatbelt.'), lt('Back control set.', 'Back control set.', 'Dos controlé.'), safetyText),
      md('dlrbt-head', 'head', lt('Đầu giữ trong', 'Head stays inside', 'Tête dedans'), lt('Giữ đầu sát hông họ, không để lộ ra ngoài khi spin.', 'Keep head near their hip, do not expose it outside during spin.', 'Garder tête près hanche, pas exposée dehors pendant spin.'), 'near', 'hide', ['head', 'neck', 'shoulders'], lt('Trong suốt quá trình spin.', 'Throughout the spin.', 'Pendant tout le spin.'), lt('Head inside tránh bị roll qua.', 'Head inside prevents being rolled over.', 'Tête dedans évite se faire rouler.'), lt('Đầu lộ ra ngoài.', 'Head exposed outside.', 'Tête exposée dehors.'), lt('Head to hip.', 'Head to hip.', 'Tête à hanche.'), lt('Cổ và đầu an toàn.', 'Neck and head are safe.', 'Cou et tête sûrs.'), safetyText),
      md('dlrbt-finish', 'finish', lt('Chốt back control', 'Lock back control', 'Verrouiller dos'), lt('Khai thác seatbelt và chest-to-back ngay sau hook placement.', 'Secure seatbelt and chest-to-back immediately after hook placement.', 'Sécuriser seatbelt et chest-to-back après hook.'), 'both', 'close_in', ['chest', 'hands', 'feet'], lt('Sau khi hook placed.', 'After hooks are placed.', 'Après hooks posés.'), lt('Chốt nhanh = back take hoàn tất.', 'Quick lock = back take complete.', 'Verrouillage rapide = prise dos finie.'), lt('Không chốt back control.', 'Not locking back control.', 'Pas verrouiller dos.'), lt('Lock now.', 'Lock now.', 'Verrouillez maintenant.'), lt('Back control ổn định.', 'Back control is stable.', 'Back control stable.'), safetyText),
    ],
    leftRightGuides: [
      guide('dlrbt-right', lt('Back take từ DLR phải.', 'Back take from right DLR.', 'Prise dos depuis DLR droite.'), lt('Tay trái giữ far hip.', 'Left hand grips far hip.', 'Main gauche grip hanche loin.'), lt('Tay phải giữ sleeve.', 'Right hand holds sleeve.', 'Main droite tient manche.'), lt('Chân trái DLR hook.', 'Left leg DLR hook.', 'Jambe gauche hook DLR.'), lt('Chân phải chuẩn bị hook back.', 'Right leg prepares back hook.', 'Jambe droite prépare hook dos.'), lt('Đầu xoay vào hông.', 'Head rotates to hip.', 'Tête tourne vers hanche.'), lt('Hông nâng lên khi spin.', 'Hips lift during spin.', 'Hanches montent pendant spin.'), lt('Far hip, spin, hook.', 'Far hip, spin, hook.', 'Hanche loin, spin, hook.')),
      guide('dlrbt-left', lt('Back take từ DLR trái.', 'Back take from left DLR.', 'Prise dos depuis DLR gauche.'), lt('Tay phải giữ far hip.', 'Right hand grips far hip.', 'Main droite grip hanche loin.'), lt('Tay trái giữ sleeve.', 'Left hand holds sleeve.', 'Main gauche tient manche.'), lt('Chân phải DLR hook.', 'Right leg DLR hook.', 'Jambe droite hook DLR.'), lt('Chân trái chuẩn bị hook back.', 'Left leg prepares back hook.', 'Jambe gauche prépare hook dos.'), lt('Đầu xoay vào hông trái.', 'Head rotates to left hip.', 'Tête tourne hanche gauche.'), lt('Hông nâng.', 'Hips lift.', 'Hanches montent.'), lt('Spin and lock.', 'Spin and lock.', 'Spin et verrouille.')),
    ],
    fastFinishPaths: [
      path('dlrbt-fast-back', lt('Đường back take nhanh', 'Fast back take path', 'Chemin prise dos rapide'), [
        { id: '1', order: 1, instruction: lt('Far hip grip.', 'Far hip grip.', 'Grip hanche loin.'), keyBodyPart: 'hands', commonMistake: lt('Bỏ grip.', 'Dropping grip.', 'Lâcher grip.') },
        { id: '2', order: 2, instruction: lt('Berimbolo spin.', 'Berimbolo spin.', 'Spin berimbolo.'), keyBodyPart: 'shoulders', commonMistake: lt('Spin không direction.', 'Spin without direction.', 'Spin sans direction.') },
        { id: '3', order: 3, instruction: lt('Place back hook.', 'Place back hook.', 'Placer hook dos.'), keyBodyPart: 'feet', commonMistake: lt('Hook thấp.', 'Hook low.', 'Hook bas.') },
        { id: '4', order: 4, instruction: lt('Seatbelt và chest-to-back.', 'Seatbelt and chest-to-back.', 'Seatbelt et chest-to-back.'), keyBodyPart: 'chest', commonMistake: lt('Không chốt back.', 'Not locking back.', 'Pas verrouiller dos.') },
      ], lt('Far hip grip và hook placed.', 'Far hip grip and hook placed.', 'Grip hanche loin et hook posé.'), lt('Họ roll qua hoặc base lại.', 'They roll through or re-base.', 'Ils roulent ou rebasent.'), lt('Vào X-guard hoặc reset DLR.', 'Go to X-guard or reset DLR.', 'Aller X-guard ou reset DLR.'), safetyText),
    ],
    troubleshootingTips: [
      { problem: lt('Không giữ được far hip.', 'Cannot hold far hip.', 'Peut pas tenir hanche loin.'), quickFix: lt('Grip sâu hơn vào belt/pants.', 'Grip deeper into belt/pants.', 'Grip plus profond ceinture/pantalon.'), cue: lt('Deep hip grip.') },
      { problem: lt('Spin không ra back.', 'Spin does not land on back.', 'Spin arrive pas dos.'), quickFix: lt('Kéo far hip mạnh hơn và xoay shoulders.', 'Pull far hip harder and rotate shoulders.', 'Tirez hanche loin plus fort et tournez épaules.'), cue: lt('Pull and spin.') },
      { problem: lt('Bị roll qua khi spin.', 'Getting rolled over during spin.', 'Se faire rouler pendant spin.'), quickFix: lt('Giữ head inside và hips over shoulders.', 'Keep head inside and hips high.', 'Gardez tête dedans et hanches hautes.'), cue: lt('Head inside.') },
    ],
    doNotDo: la(
      ['Đừng bỏ far hip grip.', 'Đừng xoay không direction.', 'Đừng để đầu lộ.', 'Đừng spin chậm.', 'Đừng quên hook placement.'],
      ['Do not drop the far hip grip.', 'Do not spin without direction.', 'Do not expose your head.', 'Do not spin slowly.', 'Do not forget the hook placement.'],
      ['Lâcher grip hanche loin.', 'Spin sans direction.', 'Tête exposée.', 'Spin lent.', 'Oublier placement hook.'],
    ),
    safetyNotes: safety,
  },
  'reverse-de-la-riva-transitions': {
    overview: lt('Transition từ RDLR bằng outside hook, hip rotation và kimura trap để vào DLR, X-guard hoặc sweep.', 'Transition from RDLR with outside hook, hip rotation, and kimura trap into DLR, X-guard, or sweep.', 'Transition depuis RDLR avec hook extérieur, rotation hanche et kimura trap vers DLR, X-guard ou sweep.'),
    topFiveDetails: [
      md('rdlr-hook', 'hook', lt('Outside hook kéo', 'Outside hook pulls', 'Hook extérieur tire'), lt('Hook ngoài kéo chân gần lên và xoay hông họ.', 'Outside hook pulls the near leg up and rotates their hip.', 'Hook extérieur tire jambe proche et tourne hanche.'), 'outside', 'pull_toward_you', ['feet', 'shins', 'hips'], lt('Khi họ đè vào RDLR.', 'When they pressure into RDLR.', 'Quand ils pressionnent RDLR.'), lt('Hook kéo mở rotation opportunity.', 'Hook pull opens rotation opportunity.', 'Hook tir ouvre rotation.'), lt('Hook không tension.', 'Hook without tension.', 'Hook sans tension.'), lt('Hook and rotate.', 'Hook and rotate.', 'Hook et tournez.'), lt('Hip rotation available.', 'Hip rotation available.', 'Rotation hanche disponible.'), safetyText),
      md('rdlr-rotation', 'angle', lt('Hip rotation ra ngoài', 'Hip rotation outward', 'Rotation hanche dehors'), lt('Xoay hông ra ngoài và đặt chân trong lên hip line.', 'Rotate hips outward and bring the inside foot to the hip line.', 'Tourner hanches dehors et pied intérieur vers hip line.'), 'far', 'rotate_right', ['hips', 'knees', 'feet'], lt('Khi hook active.', 'When the hook is active.', 'Quand hook actif.'), lt('Hip rotation mở DLR, X-guard, sweep.', 'Hip rotation opens DLR, X-guard, sweep.', 'Rotation hanche ouvre DLR, X-guard, sweep.'), lt('Không rotation.', 'No rotation.', 'Pas rotation.'), lt('Rotate then choose.', 'Rotate then choose.', 'Tournez puis choisissez.'), lt('Entry path opens.', 'Entry path opens.', 'Chemin entrée ouvre.'), safetyText),
      md('rdlr-kimura', 'grip', lt('Kimura trap option', 'Kimura trap option', 'Option kimura trap'), lt('Nếu tay họ gần, bắt kimura grip trước khi xoay.', 'If their hand is near, catch the kimura grip before rotating.', 'Si main proche, attrapez grip kimura avant rotation.'), 'both', 'pull_toward_you', ['hands', 'wrists', 'arms'], lt('Khi tay họ post gần.', 'When they post a hand nearby.', 'Quand ils postent main proche.'), lt('Kimura trap từ RDLR rất mạnh.', 'Kimura trap from RDLR is very strong.', 'Kimura trap depuis RDLR très fort.'), lt('Bỏ qua kimura trap.', 'Missing the kimura trap.', 'Manquer kimura trap.'), lt('Trap the hand.', 'Trap the hand.', 'Piégez main.'), lt('Kimura grip active.', 'Kimura grip active.', 'Grip kimura actif.'), safetyText),
      md('rdlr-dlr', 'timing', lt('Transition timing', 'Transition timing', 'Timing transition'), lt('Chọn DLR, X-guard hay sweep ngay khi họ mất base.', 'Choose DLR, X-guard, or sweep as soon as they lose base.', 'Choisir DLR, X-guard ou sweep dès qu\\'ils perdent base.'), 'both', 'drive_forward', ['feet', 'hips', 'hands'], lt('Khi rotation hoàn tất.', 'When rotation is complete.', 'Quand rotation finie.'), lt('Quyết định nhanh = transition hiệu quả.', 'Fast decision = effective transition.', 'Décision rapide = transition efficace.'), lt('Chần chờ sau rotation.', 'Hesitating after rotation.', 'Hésiter après rotation.'), lt('Choose and execute.', 'Choose and execute.', 'Choisissez et exécutez.'), lt('Transition started.', 'Transition started.', 'Transition commencée.'), safetyText),
      md('rdlr-sweep', 'finish', lt('Sweep từ RDLR', 'RDLR sweep', 'Sweep RDLR'), lt('Khi họ base yếu, sweep thẳng lên top.', 'When their base is weak, sweep straight to top.', 'Quand base faible, sweep direct vers top.'), 'both', 'drive_forward', ['feet', 'hips', 'shoulders'], lt('Khi rotation tạo angle sweep.', 'When rotation creates sweep angle.', 'Quand rotation crée angle sweep.'), lt('Sweep từ RDLR kết thúc ở side hoặc mount.', 'RDLR sweep ends in side or mount.', 'Sweep RDLR finit en side ou mount.'), lt('Không capitalize.', 'Not capitalizing.', 'Pas capitaliser.'), lt('Sweep then settle.', 'Sweep then settle.', 'Sweep puis stabilisez.'), lt('Bạn lên top.', 'You are on top.', 'Vous top.'), safetyText),
    ],
    leftRightGuides: [
      guide('rdlr-right', lt('RDLR transition phải.', 'RDLR transition right.', 'Transition RDLR droite.'), lt('Tay trái giữ sleeve.', 'Left hand holds sleeve.', 'Main gauche tient manche.'), lt('Tay phải post hip.', 'Right hand posts hip.', 'Main droite post hanche.'), lt('Chân trái RDLR hook.', 'Left leg RDLR hook.', 'Jambe gauche hook RDLR.'), lt('Chân phải rotate vào hip line.', 'Right leg rotates to hip line.', 'Jambe droite tourne hip line.'), lt('Đầu hướng theo rotation.', 'Head follows rotation.', 'Tête suit rotation.'), lt('Hông xoay ra ngoài.', 'Hips rotate outward.', 'Hanches tournent dehors.'), lt('Hook, rotate, choose.', 'Hook, rotate, choose.', 'Hook, rotation, choix.')),
      guide('rdlr-left', lt('RDLR transition trái.', 'RDLR transition left.', 'Transition RDLR gauche.'), lt('Tay phải giữ sleeve.', 'Right hand holds sleeve.', 'Main droite tient manche.'), lt('Tay trái post hip.', 'Left hand posts hip.', 'Main gauche post hanche.'), lt('Chân phải RDLR hook.', 'Right leg RDLR hook.', 'Jambe droite hook RDLR.'), lt('Chân trái rotate.', 'Left leg rotates.', 'Jambe gauche tourne.'), lt('Đầu theo rotation.', 'Head follows.', 'Tête suit.'), lt('Hông xoay ngoài.', 'Hips outward.', 'Hanches dehors.'), lt('Hook, rotate, sweep.', 'Hook, rotate, sweep.', 'Hook, rotation, sweep.')),
    ],
    fastFinishPaths: [
      path('rdlr-fast-entry', lt('Đường entry nhanh', 'Fast entry path', 'Chemin entrée rapide'), [
        { id: '1', order: 1, instruction: lt('Activate outside hook.', 'Activate outside hook.', 'Activer hook extérieur.'), keyBodyPart: 'feet', commonMistake: lt('Hook chết.', 'Dead hook.', 'Hook mort.') },
        { id: '2', order: 2, instruction: lt('Rotate hips outward.', 'Rotate hips outward.', 'Rotation hanches dehors.'), keyBodyPart: 'hips', commonMistake: lt('Không rotation.', 'No rotation.', 'Pas rotation.') },
        { id: '3', order: 3, instruction: lt('Choose entry path.', 'Choose entry path.', 'Choisir chemin entrée.'), keyBodyPart: 'feet', commonMistake: lt('Chần chờ.', 'Hesitation.', 'Hésitation.') },
        { id: '4', order: 4, instruction: lt('Execute transition.', 'Execute transition.', 'Exécuter transition.'), keyBodyPart: 'hips', commonMistake: lt('Not committed.', 'Not committed.', 'Pas engagé.') },
      ], lt('Hook active và hip rotated.', 'Hook active and hip rotated.', 'Hook actif et hanche tournée.'), lt('Họ base lại và ép.', 'They re-base and pressure.', 'Ils rebasent et pressionnent.'), lt('Reset RDLR hoặc retreat guard.', 'Reset RDLR or retreat guard.', 'Reset RDLR ou retrait garde.'), safetyText),
    ],
    troubleshootingTips: [
      { problem: lt('Hook không kéo được leg.', 'Hook cannot pull the leg.', 'Hook peut pas tirer jambe.'), quickFix: lt('Đặt hook sâu hơn.', 'Place hook deeper.', 'Placez hook plus profond.'), cue: lt('Hook deep.') },
      { problem: lt('Rotation không ra entry.', 'Rotation does not open entry.', 'Rotation ouvre pas entrée.'), quickFix: lt('Xoay hông thêm và kéo sleeve.', 'Rotate hips more and pull sleeve.', 'Tournez hanches plus et tirez manche.'), cue: lt('More hip.') },
      { problem: lt('Bỏ lỡ kimura trap.', 'Missing kimura trap.', 'Manquer kimura trap.'), quickFix: lt('Watch their hands for post.', 'Watch their hands for the post.', 'Regardez mains pour post.'), cue: lt('Find the arm.') },
    ],
    doNotDo: la(
      ['Đừng để hook chết.', 'Đừng quên xoay hông.', 'Đừng ở RDLR quá lâu.', 'Đừng bỏ lỡ hand trap.', 'Đừng sweep không follow.'],
      ['Do not let hook die.', 'Do not forget to rotate hips.', 'Do not stay in RDLR too long.', 'Do not miss the hand trap.', 'Do not sweep without follow.'],
      ['Hook mort.', 'Oublier rotation hanche.', 'Rester RDLR trop long.', 'Manquer hand trap.', 'Sweep sans suivi.'],
    ),
    safetyNotes: safety,
  },
  'z-guard-sweeps': {
    overview: lt('Sweep từ Z-guard bằng deep half entry, waiter sweep và underhook control để đảo vị trí từ bottom.', 'Sweep from Z-guard using deep half entry, waiter sweep, and underhook control to reverse from bottom.', 'Sweep depuis Z-guard avec entrée deep half, waiter sweep et underhook pour inverser depuis bottom.'),
    topFiveDetails: [
      md('zgs-underhook', 'grip', lt('Underhook deep', 'Deep underhook', 'Underhook profond'), lt('Đưa tay qua nách và bắt chặt lưng họ.', 'Slide arm through armpit and grip their back.', 'Passer bras sous aisselle et grip dos.'), 'near', 'close_in', ['hands', 'arms', 'shoulders'], lt('Khi bạn đang ở Z-guard.', 'When you are in Z-guard.', 'Quand vous êtes en Z-guard.'), lt('Underhook cho phép deep half entry.', 'Underhook enables deep half entry.', 'Underhook permet entrée deep half.'), lt('Underhook nông.', 'Shallow underhook.', 'Underhook superficiel.'), lt('Pummel deep.', 'Pummel deep.', 'Pummel profond.'), lt('Underhook chặt.', 'Underhook tight.', 'Underhook serré.'), safetyText),
      md('zgs-shield', 'knee', lt('Knee shield space', 'Knee shield space', 'Espace knee shield'), lt('Dùng knee shield để giữ khoảng cách và tạo room cho deep half.', 'Use knee shield to maintain distance and create room for deep half.', 'Utiliser knee shield pour distance et espace deep half.'), 'near', 'push_away', ['knees', 'shins', 'hips'], lt('Khi họ ép người vào.', 'When they pressure into you.', 'Quand ils pressionnent.'), lt('Shield space = deep half entry.', 'Shield space = deep half entry.', 'Espace shield = entrée deep half.'), lt('Bị ép phẳng mất space.', 'Flattened with no space.', 'Aplati sans espace.'), lt('Shield first, then enter.', 'Shield first, then enter.', 'Shield d\\'abord, puis entrée.'), lt('Space created.', 'Space created.', 'Espace créé.'), safetyText),
      md('zgs-deep-half', 'hip', lt('Deep half entry', 'Deep half entry', 'Entrée deep half'), lt('Đưa đầu vào hông họ và trượt người xuống dưới.', 'Place head to their hip and slide your body underneath.', 'Tête à leur hanche et glisser corps dessous.'), 'near', 'drive_forward', ['head', 'shoulders', 'hips'], lt('Khi underhook active.', 'When underhook is active.', 'Quand underhook actif.'), lt('Deep half neutralizes their weight.', 'Deep half neutralizes their weight.', 'Deep half neutralise leur poids.'), lt('Không vào được deep half.', 'Cannot enter deep half.', 'Peut pas entrer deep half.'), lt('Head to hip.', 'Head to hip.', 'Tête à hanche.'), lt('Bạn ở dưới họ.', 'You are underneath.', 'Vous êtes dessous.'), safetyText),
      md('zgs-waiter', 'finish', lt('Waiter sweep', 'Waiter sweep', 'Waiter sweep'), lt('Nâng chân họ bằng waiter grip và sweep qua.', 'Lift their leg with waiter grip and sweep them over.', 'Soulever leur jambe avec grip waiter et basculer.'), 'far', 'lift_up', ['feet', 'legs', 'hips'], lt('Khi deep half set.', 'When deep half is set.', 'Quand deep half posé.'), lt('Waiter sweep dùng lever của chân họ.', 'Waiter sweep uses their leg as lever.', 'Waiter sweep utilise leur jambe comme levier.'), lt('Kéo không có waiter grip.', 'Pulling without waiter grip.', 'Tirer sans grip waiter.'), lt('Waiter then sweep.', 'Waiter then sweep.', 'Waiter puis sweep.'), lt('Họ mất base và ngã.', 'They lose base and fall.', 'Ils perdent base et tombent.'), safetyText),
      md('zgs-wrestle-up', 'timing', lt('Wrestle-up backup', 'Wrestle-up backup', 'Backup wrestle-up'), lt('Nếu sweep không ra, chuyển wrestle-up bằng technical stand-up.', 'If sweep fails, transition to wrestle-up with technical stand-up.', 'Si sweep rate, transition wrestle-up avec technical stand-up.'), 'both', 'drive_forward', ['feet', 'hips', 'hands'], lt('Khi sweep blocked.', 'When sweep is blocked.', 'Quand sweep bloqué.'), lt('Wrestle-up là alternative từ Z-guard.', 'Wrestle-up is alternative from Z-guard.', 'Wrestle-up est alternative depuis Z-guard.'), lt('Nằm chờ sweep.', 'Waiting flat for sweep.', 'Attendre plat pour sweep.'), lt('Stand-up then attack.', 'Stand-up then attack.', 'Levez-vous puis attaquez.'), lt('Bạn ở tư thế đứng.', 'You are in a standing position.', 'Position debout.'), safetyText),
    ],
    leftRightGuides: [
      guide('zgs-right', lt('Z-guard sweep phải.', 'Z-guard sweep right.', 'Sweep Z-guard droite.'), lt('Tay trái underhook.', 'Left hand underhook.', 'Main gauche underhook.'), lt('Tay phải post mat.', 'Right hand posts mat.', 'Main droite post sol.'), lt('Chân trái knee shield.', 'Left leg knee shield.', 'Jambe gauche knee shield.'), lt('Chân phải waiter hook.', 'Right leg waiter hook.', 'Jambe droite hook waiter.'), lt('Đầu vào hông.', 'Head to hip.', 'Tête à hanche.'), lt('Hông xoay dưới họ.', 'Hips under them.', 'Hanches sous eux.'), lt('Shield, underhook, sweep.', 'Shield, underhook, sweep.', 'Shield, underhook, sweep.')),
      guide('zgs-left', lt('Z-guard sweep trái.', 'Z-guard sweep left.', 'Sweep Z-guard gauche.'), lt('Tay phải underhook.', 'Right hand underhook.', 'Main droite underhook.'), lt('Tay trái post mat.', 'Left hand posts mat.', 'Main gauche post sol.'), lt('Chân phải knee shield.', 'Right leg knee shield.', 'Jambe droite knee shield.'), lt('Chân trái waiter hook.', 'Left leg waiter hook.', 'Jambe gauche hook waiter.'), lt('Đầu vào hông.', 'Head to hip.', 'Tête à hanche.'), lt('Hông xoay dưới.', 'Hips under.', 'Hanches sous.'), lt('Deep half then sweep.', 'Deep half then sweep.', 'Deep half puis sweep.')),
    ],
    fastFinishPaths: [
      path('zgs-fast-sweep', lt('Đường sweep nhanh', 'Fast sweep path', 'Chemin sweep rapide'), [
        { id: '1', order: 1, instruction: lt('Knee shield tạo space.', 'Knee shield creates space.', 'Knee shield crée espace.'), keyBodyPart: 'knees', commonMistake: lt('Bị ép phẳng.', 'Getting flattened.', 'Aplati.') },
        { id: '2', order: 2, instruction: lt('Pummel underhook.', 'Pummel underhook.', 'Pummel underhook.'), keyBodyPart: 'hands', commonMistake: lt('Underhook nông.', 'Shallow underhook.', 'Underhook superficiel.') },
        { id: '3', order: 3, instruction: lt('Vào deep half.', 'Enter deep half.', 'Entrer deep half.'), keyBodyPart: 'head', commonMistake: lt('Không vào được.', 'Cannot enter.', 'Peut pas entrer.') },
        { id: '4', order: 4, instruction: lt('Waiter sweep lên top.', 'Waiter sweep to top.', 'Waiter sweep top.'), keyBodyPart: 'feet', commonMistake: lt('Không sweep.', 'No sweep.', 'Pas sweep.') },
      ], lt('Underhook sâu và waiter grip.', 'Deep underhook and waiter grip.', 'Underhook profond et grip waiter.'), lt('Họ base và ép mạnh.', 'They base and press hard.', 'Ils basent et pressionnent fort.'), lt('Wrestle-up hoặc reset half guard.', 'Wrestle-up or reset half guard.', 'Wrestle-up ou reset half guard.'), safetyText),
    ],
    troubleshootingTips: [
      { problem: lt('Không vào được deep half.', 'Cannot enter deep half.', 'Peut pas entrer deep half.'), quickFix: lt('Shield rộng hơn và pummel underhook sâu.', 'Widen shield and pummel underhook deeper.', 'Élargissez shield et pummel underhook profond.'), cue: lt('Space then enter.') },
      { problem: lt('Sweep không lật được họ.', 'Sweep cannot flip them.', 'Sweep peut pas les renverser.'), quickFix: lt('Dùng waiter grip nâng leg họ cao hơn.', 'Use waiter grip to lift their leg higher.', 'Grip waiter pour lever jambe plus haut.'), cue: lt('Lift their leg.') },
      { problem: lt('Bị flatten khi shield.', 'Getting flattened on shield.', 'Aplati sur shield.'), quickFix: lt('Đẩy hông ra xa hơn và giữ shield active.', 'Push hips farther and keep shield active.', 'Poussez hanches plus loin et gardez shield actif.'), cue: lt('Active shield.') },
    ],
    doNotDo: la(
      ['Đừng để bị flatten.', 'Đừng underhook nông.', 'Đừng ở Z-guard quá passive.', 'Đừng quên waiter grip.', 'Đừng sweep không có angle.'],
      ['Do not get flattened.', 'Do not use shallow underhook.', 'Do not stay passive in Z-guard.', 'Do not forget the waiter grip.', 'Do not sweep without angle.'],
      ['Aplati.', 'Underhook superficiel.', 'Rester passif Z-guard.', 'Oublier grip waiter.', 'Sweep sans angle.'],
    ),
    safetyNotes: safety,
  },
  'knee-on-belly-control': {
    overview: lt('Kiểm soát knee on belly bằng gối nặng, far hip grip và shoulder isolation để kiểm soát và chuyển vị trí.', 'Control knee on belly with heavy knee, far hip grip, and shoulder isolation to control and transition.', 'Contrôler genou ventre avec genou lourd, grip hanche loin et isolation épaule pour contrôler et transiter.'),
    topFiveDetails: [
      md('kob-knee', 'pressure', lt('Gối nặng trên bụng', 'Knee heavy on belly', 'Genou lourd sur ventre'), lt('Đặt gối nặng lên bụng hoặc sternum, không trên ribs.', 'Place knee heavy on belly or sternum, not on ribs.', 'Placer genou lourd sur ventre ou sternum, pas côtes.'), 'near', 'drive_down', ['knees', 'hips', 'belly'], lt('Khi vừa lên KOB.', 'When you first get to KOB.', 'Quand vous arrivez KOB.'), lt('Knee nặng làm họ khó bridge.', 'Heavy knee makes bridging hard.', 'Genou lourd rend bridge difficile.'), lt('Knee trên ribs.', 'Knee on ribs.', 'Genou sur côtes.'), lt('Weight through knee.', 'Weight through knee.', 'Poids à travers genou.'), lt('Họ không thể bridge.', 'They cannot bridge.', 'Ils peuvent pas bridge.'), safetyText),
      md('kob-far-hip', 'grip', lt('Far hip control', 'Far hip control', 'Contrôle hanche loin'), lt('Grip far hip belt/pants để kiểm soát hướng hông họ.', 'Grip far hip belt/pants to control their hip direction.', 'Grip ceinture/pantalon hanche loin pour diriger hanche.'), 'far', 'pin_in', ['hands', 'hips', 'fingers'], lt('Khi knee on belly set.', 'When KOB is set.', 'Quand KOB posé.'), lt('Far hip grip ngăn họ xoay vào trong.', 'Far hip grip prevents them from turning in.', 'Grip hanche loin empêche tourner dedans.'), lt('Buông far hip.', 'Releasing far hip.', 'Lâcher hanche loin.'), lt('Grip the far hip.', 'Grip the far hip.', 'Grip hanche loin.'), lt('Họ khó xoay.', 'They cannot turn easily.', 'Peuvent pas tourner facilement.'), safetyText),
      md('kob-shoulder', 'grip', lt('Shoulder isolation', 'Shoulder isolation', 'Isolation épaule'), lt('Pull elbow ra khỏi ribs để cô lập shoulder họ.', 'Pull elbow away from ribs to isolate their shoulder.', 'Tirer coude des côtes pour isoler épaule.'), 'near', 'pull_toward_you', ['elbows', 'shoulders', 'arms'], lt('Khi bạn muốn attack arm hoặc back.', 'When you want to attack arm or back.', 'Quand vous voulez attaquer bras ou dos.'), lt('Shoulder isolation mở kimura và back take.', 'Shoulder isolation opens kimura and back take.', 'Isolation épaule ouvre kimura et prise dos.'), lt('Elbow gần ribs.', 'Elbow near ribs.', 'Coude près côtes.'), lt('Pull the elbow.', 'Pull the elbow.', 'Tirez le coude.'), lt('Shoulder họ lộ.', 'Their shoulder is exposed.', 'Épaule exposée.'), safetyText),
      md('kob-transition', 'timing', lt('Transition timing', 'Transition timing', 'Timing transition'), lt('Không ở KOB quá 5 giây, chuyển mount, back hoặc submission.', 'Do not stay in KOB over 5 seconds; transition to mount, back, or submission.', 'Ne pas rester KOB plus de 5s; transition mount, dos ou soumission.'), 'both', 'drive_forward', ['hips', 'feet', 'hands'], lt('Khi KOB control active.', 'When KOB control is active.', 'Quand KOB contrôle actif.'), lt('KOB là transition position.', 'KOB is a transition position.', 'KOB est une transition.'), lt('Ở KOB quá lâu.', 'Staying in KOB too long.', 'Rester KOB trop long.'), lt('Transition then attack.', 'Transition then attack.', 'Transition puis attaque.'), lt('Bạn đã chuyển vị trí.', 'You have transitioned.', 'Vous avez transité.'), safetyText),
      md('kob-back-threat', 'angle', lt('Back take angle', 'Back take angle', 'Angle prise dos'), lt('Xoay hông và kéo far hip để lộ back họ.', 'Rotate hips and pull far hip to expose their back.', 'Tourner hanches et tirer hanche loin pour exposer dos.'), 'both', 'rotate_right', ['hips', 'hands', 'shoulders'], lt('Khi họ turn away.', 'When they turn away.', 'Quand ils tournent ailleurs.'), lt('KOB back take là nhánh mạnh.', 'KOB back take is a strong branch.', 'Prise dos KOB est branche forte.'), lt('Bỏ qua back take khi họ xoay.', 'Missing back take when they turn.', 'Manquer prise dos quand ils tournent.'), lt('Pull and follow.', 'Pull and follow.', 'Tirez et suivez.'), lt('Back exposure.', 'Back exposure.', 'Dos exposé.'), safetyText),
    ],
    leftRightGuides: [
      guide('kob-right', lt('KOB khi gối phải.', 'KOB with right knee.', 'KOB genou droit.'), lt('Tay trái far hip grip.', 'Left hand far hip grip.', 'Main gauche grip hanche loin.'), lt('Tay phải shoulder kiểm soát.', 'Right hand shoulder control.', 'Main droite contrôle épaule.'), lt('Chân trái base wide.', 'Left leg wide base.', 'Jambe gauche base large.'), lt('Chân phải KOB.', 'Right leg KOB.', 'Jambe droite KOB.'), lt('Đầu cao.', 'Head up.', 'Tête haute.'), lt('Hông nặng trên gối.', 'Hips heavy on knee.', 'Hanches lourdes genou.'), lt('Grip, control, transition.', 'Grip, control, transition.', 'Grip, contrôle, transition.')),
      guide('kob-left', lt('KOB khi gối trái.', 'KOB with left knee.', 'KOB genou gauche.'), lt('Tay phải far hip grip.', 'Right hand far hip grip.', 'Main droite grip hanche loin.'), lt('Tay trái shoulder control.', 'Left hand shoulder control.', 'Main gauche contrôle épaule.'), lt('Chân phải base wide.', 'Right leg wide base.', 'Jambe droite base large.'), lt('Chân trái KOB.', 'Left leg KOB.', 'Jambe gauche KOB.'), lt('Đầu cao.', 'Head up.', 'Tête haute.'), lt('Hông heavy.', 'Hips heavy.', 'Hanches lourdes.'), lt('5 seconds, then move.', '5 seconds, then move.', '5 secondes, puis bougez.')),
    ],
    fastFinishPaths: [
      path('kob-fast-path', lt('Đường control nhanh', 'Fast control path', 'Chemin contrôle rapide'), [
        { id: '1', order: 1, instruction: lt('Set knee heavy.', 'Set knee heavy.', 'Poser genou lourd.'), keyBodyPart: 'knees', commonMistake: lt('Gối trên ribs.', 'Knee on ribs.', 'Genou sur côtes.') },
        { id: '2', order: 2, instruction: lt('Far hip grip.', 'Far hip grip.', 'Grip hanche loin.'), keyBodyPart: 'hands', commonMistake: lt('Buông far hip.', 'Release far hip.', 'Lâcher hanche loin.') },
        { id: '3', order: 3, instruction: lt('Pull elbow out.', 'Pull elbow out.', 'Tirer coude dehors.'), keyBodyPart: 'elbows', commonMistake: lt('Elbow kín.', 'Elbow tight.', 'Coude serré.') },
        { id: '4', order: 4, instruction: lt('Chọn transition: mount/back.', 'Choose transition: mount/back.', 'Choisir transition: mount/dos.'), keyBodyPart: 'hips', commonMistake: lt('Ở KOB quá lâu.', 'Stay in KOB too long.', 'Rester KOB trop long.') },
      ], lt('Knee nặng, far hip grip.', 'Knee heavy, far hip grip.', 'Genou lourd, grip hanche loin.'), lt('Họ bridge và xoay vào.', 'They bridge and turn in.', 'Ils bridge et tournent dedans.'), lt('Chuyển lại về side control.', 'Return to side control.', 'Retour side control.'), safetyText),
    ],
    troubleshootingTips: [
      { problem: lt('KOB không nặng.', 'KOB is not heavy.', 'KOB pas lourd.'), quickFix: lt('Đưa hông lên trên gối và drop weight.', 'Bring hips over knee and drop weight.', 'Amenez hanches sur genou et lâchez poids.'), cue: lt('Weight drop.') },
      { problem: lt('Họ turn vào trong.', 'They turn in.', 'Ils tournent dedans.'), quickFix: lt('Far hip grip kéo ra và back take.', 'Pull far hip and back take.', 'Tirez hanche loin et prise dos.'), cue: lt('Back take now.') },
      { problem: lt('Không quyết định transition.', 'Cannot decide transition.', 'Peut pas décider transition.'), quickFix: lt('Chọn mount hoặc back trước.', 'Choose mount or back before KOB.', 'Choisir mount ou dos avant KOB.'), cue: lt('Decide first.') },
    ],
    doNotDo: la(
      ['Đừng để KOB quá lâu.', 'Đừng bỏ far hip grip.', 'Đừng để gối trên ribs.', 'Đừng quên back take option.', 'Đừng stay passive trên KOB.'],
      ['Do not stay in KOB too long.', 'Do not drop far hip grip.', 'Do not keep knee on ribs.', 'Do not forget the back take.', 'Do not stay passive on KOB.'],
      ['Rester KOB trop long.', 'Lâcher hanche loin.', 'Genou sur côtes.', 'Oublier prise dos.', 'Passif KOB.'],
    ),
    safetyNotes: safety,
  },
  'north-south-control': {
    overview: lt('Kiểm soát north south bằng shoulder pressure, arm control và choke threat để control và chuyển mount/side.', 'Control north south with shoulder pressure, arm control, and choke threat to control and transition to mount/side.', 'Contrôler north south avec pression épaule, contrôle bras et menace choke pour contrôler et transiter mount/side.'),
    topFiveDetails: [
      md('ns-shoulder-press', 'pressure', lt('Shoulder pressure trên cổ', 'Shoulder pressure on neck', 'Pression épaule sur cou'), lt('Đặt shoulder nặng lên cổ/ngực họ và drive chéo.', 'Place shoulder heavily on their neck/chest and drive diagonally.', 'Placer épaule lourde sur cou/poitrine et pousser diagonale.'), 'near', 'drive_diagonal', ['shoulders', 'chest', 'neck'], lt('Khi bạn đến NS.', 'When you enter NS.', 'Quand vous arrivez NS.'), lt('Shoulder pressure ngăn họ bridge.', 'Shoulder pressure prevents bridging.', 'Pression épaule empêche bridge.'), lt('Không có shoulder contact.', 'No shoulder contact.', 'Pas contact épaule.'), lt('Drive through the shoulder.', 'Drive through the shoulder.', 'Poussez à travers épaule.'), lt('Họ bị ép thấp.', 'They are pressed low.', 'Ils sont pressés bas.'), safetyText),
      md('ns-arm-traps', 'grip', lt('Arm control', 'Arm control', 'Contrôle bras'), lt('Pin hai tay họ xuống thảm hoặc kẹp bằng nách.', 'Pin both arms to the mat or trap them with armpits.', 'Bloquer bras au sol ou piéger avec aisselles.'), 'both', 'pin_in', ['hands', 'arms', 'elbows'], lt('Khi shoulder pressure active.', 'When shoulder pressure is active.', 'Quand pression épaule active.'), lt('Arm control ngăn họ frame.', 'Arm control prevents framing.', 'Contrôle bras empêche frame.'), lt('Để tay tự do.', 'Leaving arms free.', 'Laisser bras libres.'), lt('Pin the arms.', 'Pin the arms.', 'Bloquez les bras.'), lt('Họ không thể post.', 'They cannot post.', 'Peuvent pas poster.'), safetyText),
      md('ns-choke', 'finish', lt('North south choke', 'North south choke', 'Étranglement north south'), lt('Dùng forearm cắt line cổ từ dưới nách họ.', 'Use forearm to cut the neck line from under their armpit.', 'Utiliser avant-bras pour couper ligne cou sous aisselle.'), 'right', 'close_in', ['forearms', 'neck', 'arms'], lt('Khi arms pinned.', 'When arms are pinned.', 'Quand bras bloqués.'), lt('NS choke là submission chính từ NS.', 'NS choke is the main submission from NS.', 'NS choke est soumission principale depuis NS.'), lt('Forearm sai line.', 'Forearm on wrong line.', 'Avant-bras mauvaise ligne.'), lt('Chest down, forearm across.', 'Chest down, forearm across.', 'Poitrine bas, avant-bras traversé.'), lt('Choke line clean.', 'Choke line clean.', 'Ligne choke propre.'), safetyText),
      md('ns-hip-ride', 'hip', lt('Hip ride control', 'Hip ride control', 'Contrôle ride hanche'), lt('Giữ hông thấp và ride hip line để không bị xoay.', 'Keep hips low and ride their hip line to avoid being turned.', 'Garder hanches basses et rider hip line pour pas tourner.'), 'both', 'drive_down', ['hips', 'knees', 'feet'], lt('Khi họ cố xoay.', 'When they try to turn.', 'Quand ils essaient tourner.'), lt('Hip ride ngăn escape và giữ pin.', 'Hip ride prevents escape and keeps pin.', 'Hip ride empêche sortie et garde pin.'), lt('Hông cao và nổi.', 'Hips high and floating.', 'Hanches hautes et flottantes.'), lt('Stay low.', 'Stay low.', 'Restez bas.'), lt('Không escape path.', 'No escape path.', 'Pas chemin sortie.'), safetyText),
      md('ns-transition', 'timing', lt('Transition timing', 'Transition timing', 'Timing transition'), lt('Nếu choke không vào, chuyển side control hoặc mount.', 'If the choke does not land, transition to side control or mount.', 'Si choke marche pas, transition side control ou mount.'), 'both', 'drive_diagonal', ['hips', 'feet', 'hands'], lt('Khi choke line không clean.', 'When the choke line is not clean.', 'Quand ligne choke pas propre.'), lt('Transition nhanh giữ vị trí top.', 'Fast transition keeps top position.', 'Transition rapide garde top.'), lt('Cố choke quá lâu.', 'Forcing choke too long.', 'Forcer choke trop long.'), lt('Branch to side.', 'Branch to side.', 'Branchez side.'), lt('Position changed.', 'Position changed.', 'Position changée.'), safetyText),
    ],
    leftRightGuides: [
      guide('ns-right', lt('NS khi đầu bạn phải.', 'NS when your head is right.', 'NS tête droite.'), lt('Tay trái pin arm.', 'Left hand pins arm.', 'Main gauche bloque bras.'), lt('Tay phải choke line.', 'Right hand choke line.', 'Main droite ligne choke.'), lt('Chân trái base wide.', 'Left leg wide base.', 'Jambe gauche base large.'), lt('Chân phải base.', 'Right leg base.', 'Jambe droite base.'), lt('Đầu sát ngực họ.', 'Head close to their chest.', 'Tête près leur poitrine.'), lt('Hông thấp.', 'Hips low.', 'Hanches basses.'), lt('Shoulder, arms, choke.', 'Shoulder, arms, choke.', 'Épaule, bras, choke.')),
      guide('ns-left', lt('NS khi đầu bạn trái.', 'NS when your head is left.', 'NS tête gauche.'), lt('Tay phải pin arm.', 'Right hand pins arm.', 'Main droite bloque bras.'), lt('Tay trái choke line.', 'Left hand choke line.', 'Main gauche ligne choke.'), lt('Chân phải base wide.', 'Right leg wide base.', 'Jambe droite base large.'), lt('Chân trái base.', 'Left leg base.', 'Jambe gauche base.'), lt('Đầu sát ngực.', 'Head close to chest.', 'Tête près poitrine.'), lt('Hông thấp.', 'Hips low.', 'Hanches basses.'), lt('Pressure then choke.', 'Pressure then choke.', 'Pression puis choke.')),
    ],
    fastFinishPaths: [
      path('ns-fast-choke', lt('Đường choke nhanh', 'Fast choke path', 'Chemin choke rapide'), [
        { id: '1', order: 1, instruction: lt('Shoulder pressure set.', 'Shoulder pressure set.', 'Pression épaule posée.'), keyBodyPart: 'shoulders', commonMistake: lt('Không shoulder contact.', 'No shoulder contact.', 'Pas contact épaule.') },
        { id: '2', order: 2, instruction: lt('Pin arms to mat.', 'Pin arms to mat.', 'Bloquer bras au sol.'), keyBodyPart: 'hands', commonMistake: lt('Tay tự do.', 'Free arms.', 'Bras libres.') },
        { id: '3', order: 3, instruction: lt('Forearm on neck line.', 'Forearm on neck line.', 'Avant-bras ligne cou.'), keyBodyPart: 'forearms', commonMistake: lt('Forearm sai line.', 'Forearm off line.', 'Avant-bras hors ligne.') },
        { id: '4', order: 4, instruction: lt('Chest down for choke.', 'Chest down for choke.', 'Poitrine bas pour choke.'), keyBodyPart: 'chest', commonMistake: lt('Chest nâng.', 'Chest up.', 'Poitrine haut.') },
      ], lt('Shoulder trên cổ, arms bị pin.', 'Shoulder on neck, arms pinned.', 'Épaule sur cou, bras bloqués.'), lt('Họ bridge và turn.', 'They bridge and turn.', 'Ils bridge et tournent.'), lt('Chuyển side control.', 'Switch to side control.', 'Changer side control.'), safetyText),
    ],
    troubleshootingTips: [
      { problem: lt('Không có shoulder pressure.', 'No shoulder pressure.', 'Pas pression épaule.'), quickFix: lt('Drive shoulder chéo qua chest họ.', 'Drive shoulder diagonally across their chest.', 'Poussez épaule diagonale poitrine.'), cue: lt('Shoulder drive.') },
      { problem: lt('Tay họ frame.', 'Their arms frame.', 'Leurs bras framment.'), quickFix: lt('Pin arms xuống mat bằng nách.', 'Pin arms to mat with armpits.', 'Bloquez bras au sol avec aisselles.'), cue: lt('Pin arms.') },
      { problem: lt('Họ xoay ra khỏi NS.', 'They turn out of NS.', 'Ils tournent hors NS.'), quickFix: lt('Follow với hip ride và side control.', 'Follow with hip ride and side control.', 'Suivez hip ride et side control.'), cue: lt('Follow and side.') },
    ],
    doNotDo: la(
      ['Đừng để shoulder không pressure.', 'Đừng bỏ arm control.', 'Đừng cố choke không line.', 'Đừng ở NS quá lâu.', 'Đừng quên transition option.'],
      ['Do not lose shoulder pressure.', 'Do not drop arm control.', 'Do not choke without the line.', 'Do not stay in NS too long.', 'Do not forget the transition option.'],
      ['Perdre pression épaule.', 'Lâcher contrôle bras.', 'Choke sans ligne.', 'Rester NS trop long.', 'Oublier option transition.'],
    ),
    safetyNotes: safety,
  },
  'inverted-guard-control': {
    overview: lt('Inverted guard dùng invert angles để đặt chân lên hip/shoulder line và kết nối K-guard, matrix hoặc leg entry.', 'Inverted guard uses invert angles to place feet on hip/shoulder line and connect to K-guard, matrix, or leg entries.', 'Garde inversée utilise angles inversion pour pieds sur hip/shoulder line et connexion K-guard, matrix ou entrées jambes.'),
    topFiveDetails: [
      md('ig-invert', 'angle', lt('Invert safety', 'Invert safety', 'Sécurité inversion'), lt('Xoay shoulders trước, đưa hông qua head, giữ cổ an toàn.', 'Rotate shoulders first, bring hips over head, keep neck safe.', 'Tourner épaules d\\'abord, hanches par-dessus tête, cou sûr.'), 'both', 'rotate_left', ['shoulders', 'hips', 'spine'], lt('Khi muốn invert vào guard.', 'When you want to invert into guard.', 'Quand vous voulez inverser garde.'), lt('Invert đúng kỹ thuật bảo vệ cổ.', 'Correct invert protects the neck.', 'Inversion correcte protège cou.'), lt('Invert bằng cổ.', 'Inverting with the neck.', 'Inverser avec cou.'), lt('Shoulders first.', 'Shoulders first.', 'Épaules d\\'abord.'), lt('Cổ không có áp lực.', 'No neck pressure.', 'Pas pression cou.'), safetyText),
      md('ig-foot-placement', 'hook', lt('Foot trên hip/shoulder', 'Foot on hip/shoulder', 'Pied sur hanche/épaule'), lt('Đặt chân lên hip line hoặc shoulder line để tạo base.', 'Place foot on hip line or shoulder line to create base.', 'Placer pied sur hip line ou shoulder line pour base.'), 'both', 'close_in', ['feet', 'hips', 'shoulders'], lt('Khi invert hoàn tất.', 'When invert is complete.', 'Quand inversion finie.'), lt('Foot placement mở K-guard và matrix entry.', 'Foot placement opens K-guard and matrix entries.', 'Placement pied ouvre K-guard et matrix.'), lt('Chân treo không target.', 'Feet hanging without target.', 'Pieds pendants sans cible.'), lt('Feet to hip/shoulder.', 'Feet to hip/shoulder.', 'Pieds vers hanche/épaule.'), lt('Entry path opens.', 'Entry path opens.', 'Chemin entrée ouvert.'), safetyText),
      md('ig-k-guard', 'hook', lt('K-guard connection', 'K-guard connection', 'Connexion K-guard'), lt('Shin kết nối hông họ và kéo lại để vào K-guard.', 'Shin connects to their hip and pulls to enter K-guard.', 'Tibia connecte leur hanche et tire pour K-guard.'), 'inside', 'pull_toward_you', ['knees', 'shins', 'hips'], lt('Khi foot đã placed.', 'When foot is placed.', 'Quand pied placé.'), lt('K-guard cho phép leg attack và sweep.', 'K-guard allows leg attack and sweep.', 'K-guard permet attaque jambe et sweep.'), lt('Shin xa hông.', 'Shin far from hip.', 'Tibia loin hanche.'), lt('Shin to hip.', 'Shin to hip.', 'Tibia à hanche.'), lt('K-guard active.', 'K-guard active.', 'K-guard actif.'), safetyText),
      md('ig-matrix', 'finish', lt('Matrix entry', 'Matrix entry', 'Entrée matrix'), lt('Đẩy hông lên và xoay người để vào matrix position.', 'Push hips up and rotate body to enter matrix position.', 'Pousser hanches haut et tourner corps pour position matrix.'), 'both', 'drive_forward', ['legs', 'hips', 'feet'], lt('Khi K-guard set.', 'When K-guard is set.', 'Quand K-guard posé.'), lt('Matrix position cho phép leg attack from top angle.', 'Matrix allows leg attack from top angle.', 'Matrix permet attaque jambe angle top.'), lt('Không commit vào matrix.', 'Not committing to matrix.', 'Pas engager matrix.'), lt('Push and rotate.', 'Push and rotate.', 'Poussez et tournez.'), lt('Matrix position reached.', 'Matrix position reached.', 'Position matrix atteinte.'), safetyText),
      md('ig-leg-entry', 'timing', lt('Leg entry or sweep', 'Leg entry or sweep', 'Entrée jambe ou sweep'), lt('Chọn leg attack entry hoặc sweep từ matrix/K-guard.', 'Choose leg attack entry or sweep from matrix/K-guard.', 'Choisir entrée attaque jambe ou sweep depuis matrix/K-guard.'), 'both', 'drive_forward', ['legs', 'feet', 'hips'], lt('Khi entry path open.', 'When entry path is open.', 'Quand chemin entrée ouvert.'), lt('Decision timing quyết định success.', 'Decision timing determines success.', 'Timing décision détermine succès.'), lt('Không quyết định.', 'No decision.', 'Pas décision.'), lt('Choose and attack.', 'Choose and attack.', 'Choisissez et attaquez.'), lt('Leg attack or sweep active.', 'Leg attack or sweep active.', 'Attaque jambe ou sweep actif.'), safetyText),
    ],
    leftRightGuides: [
      guide('ig-right', lt('Invert khi nghiêng phải.', 'Invert when tilting right.', 'Inverser inclinaison droite.'), lt('Tay trái post mat.', 'Left hand posts mat.', 'Main gauche post sol.'), lt('Tay phải guide hips.', 'Right hand guides hips.', 'Main droite guide hanches.'), lt('Chân trái invert pivot.', 'Left leg invert pivot.', 'Jambe gauche pivot inversion.'), lt('Chân phải foot placed.', 'Right leg foot placed.', 'Jambe droite pied placé.'), lt('Đầu xoay theo shoulders.', 'Head follows shoulders.', 'Tête suit épaules.'), lt('Hông đưa qua head.', 'Hips go over head.', 'Hanches par-dessus tête.'), lt('Shoulders first, then hips.', 'Shoulders first, then hips.', 'Épaules d\\'abord, puis hanches.')),
      guide('ig-left', lt('Invert khi nghiêng trái.', 'Invert when tilting left.', 'Inverser inclinaison gauche.'), lt('Tay phải post mat.', 'Right hand posts mat.', 'Main droite post sol.'), lt('Tay trái guide hips.', 'Left hand guides hips.', 'Main gauche guide hanches.'), lt('Chân phải invert pivot.', 'Right leg invert pivot.', 'Jambe droite pivot inversion.'), lt('Chân trái foot placed.', 'Left leg foot placed.', 'Jambe gauche pied placé.'), lt('Đầu theo shoulders.', 'Head follows shoulders.', 'Tête suit épaules.'), lt('Hông qua head.', 'Hips over head.', 'Hanches par-dessus tête.'), lt('Invert, place, enter.', 'Invert, place, enter.', 'Inverse, place, entre.')),
    ],
    fastFinishPaths: [
      path('ig-fast-entry', lt('Đường entry nhanh', 'Fast entry path', 'Chemin entrée rapide'), [
        { id: '1', order: 1, instruction: lt('Shoulder rotation invert.', 'Shoulder rotation invert.', 'Inversion rotation épaules.'), keyBodyPart: 'shoulders', commonMistake: lt('Dùng cổ.', 'Using neck.', 'Utiliser cou.') },
        { id: '2', order: 2, instruction: lt('Foot trên hip line.', 'Foot on hip line.', 'Pied sur hip line.'), keyBodyPart: 'feet', commonMistake: lt('Chân treo.', 'Foot hanging.', 'Pied pendant.') },
        { id: '3', order: 3, instruction: lt('K-guard shin connection.', 'K-guard shin connection.', 'Connexion shin K-guard.'), keyBodyPart: 'knees', commonMistake: lt('Shin xa.', 'Shin far.', 'Tibia loin.') },
        { id: '4', order: 4, instruction: lt('Matrix entry or sweep.', 'Matrix entry or sweep.', 'Matrix entry ou sweep.'), keyBodyPart: 'legs', commonMistake: lt('Không quyết định.', 'No decision.', 'Pas décision.') },
      ], lt('Foot placed và K-guard connected.', 'Foot placed and K-guard connected.', 'Pied placé et K-guard connecté.'), lt('Mất invert angle.', 'Losing invert angle.', 'Perdre angle inversion.'), lt('Retreat to guard or reset.', 'Retreat to guard or reset.', 'Retrait garde ou reset.'), safetyText),
    ],
    troubleshootingTips: [
      { problem: lt('Đau cổ khi invert.', 'Neck pain during invert.', 'Douleur cou inversion.'), quickFix: lt('Shoulders xoay trước và đưa hông qua head.', 'Rotate shoulders first, bring hips over head.', 'Tournez épaules d\\'abord, hanches par-dessus tête.'), cue: lt('Shoulders first.') },
      { problem: lt('Không kết nối được K-guard.', 'Cannot connect K-guard.', 'Peut pas connecter K-guard.'), quickFix: lt('Shin kéo sâu vào hông họ.', 'Shin pull deeper into their hip.', 'Tibia tire plus profond leur hanche.'), cue: lt('Shin deep.') },
      { problem: lt('Entry không có timing.', 'Entry has no timing.', 'Entrée sans timing.'), quickFix: lt('Chọn entry ngay khi foot placed.', 'Choose entry as soon as foot is placed.', 'Choisir entrée dès pied placé.'), cue: lt('Choose fast.') },
    ],
    doNotDo: la(
      ['Đừng invert bằng cổ.', 'Đừng để chân treo không target.', 'Đừng ở inverted quá lâu.', 'Đừng quên K-guard connection.', 'Đừng chần chờ entry timing.'],
      ['Do not invert with the neck.', 'Do not let feet hang without target.', 'Do not stay inverted too long.', 'Do not forget K-guard connection.', 'Do not hesitate on entry timing.'],
      ['Inverser avec cou.', 'Pieds pendants sans cible.', 'Rester inversé trop long.', 'Oublier connexion K-guard.', 'Hésiter timing entrée.'],
    ),
    safetyNotes: safetyLeg,
  },
"""

with open('scripts/micro_entries.py', 'w') as f:
    f.write('ENTRIES = ' + repr(micro_entries))

# Find insertion point in microDetailSystems.ts
# We need to insert before the closing `}` of the systems object
# Pattern: find `},\n}` at the end of the file (last entry close + object close)
obj_close = '\n}\n\nObject.assign(systems, extraMicroDetailSystems)'
idx = micro_content.rfind('\n  },\n}\n\nObject.assign(systems, extraMicroDetailSystems)')
if idx == -1:
    # Try alternative pattern
    idx = micro_content.rfind('  },\n}\n')
    if idx != -1:
        # Insert after the last entry close
        new_content = micro_content[:idx+5] + '\n' + micro_entries + '\n' + micro_content[idx+5:]
        with open('src/data/microDetailSystems.ts', 'w') as f:
            f.write(new_content)
        print("microDetailSystems.ts: inserted entries successfully")
    else:
        print("microDetailSystems.ts: could not find insertion point")
else:
    idx = idx + len('\n  },\n')
    new_content = micro_content[:idx] + '\n' + micro_entries + '\n' + micro_content[idx:]
    with open('src/data/microDetailSystems.ts', 'w') as f:
        f.write(new_content)
    print("microDetailSystems.ts: inserted entries successfully")
