import fs from 'fs';

// Load existing translations from qualityChecklists.ts
const qc = fs.readFileSync('src/data/qualityChecklists.ts', 'utf8');
const qcMatches = [...qc.matchAll(/lt\('([^']*)'\s*,\s*'([^']*)'/g)];
const qcMap = {};
for (const m of qcMatches) {
  if (m[1] !== m[2] && m[1] !== '' && m[2] !== '') {
    qcMap[m[2]] = m[1];
  }
}
console.log(`Loaded ${Object.keys(qcMap).length} existing translations from qualityChecklists.ts`);

// Complete EN→VI translation mapping for all 286 unique phrases
// Reuses qualityChecklists.ts translations where available, adds new translations for the rest
const enToVi = {
  // === From qualityChecklists.ts (reuse) ===
  ...qcMap,

  // === NEW translations specific to microDetailSystems.ts ===
  'Active hips.': 'Hông sống.',
  'Angle in.': 'Góc vào.',
  'Angle it.': 'Tạo góc.',
  'Angle then settle.': 'Góc rồi ổn định.',
  'Arch and look back.': 'Ưỡn và nhìn lại.',
  'Arm across.': 'Tay qua.',
  'Block hands.': 'Chặn tay.',
  'Block the frame.': 'Chặn frame.',
  'Block the hip.': 'Chặn hông.',
  'Bone frame.': 'Frame xương.',
  'Branch early to side or back.': 'Branch sớm sang side hoặc back.',
  'Branch if they sit up.': 'Branch nếu họ ngồi dậy.',
  'Branch if they turn in.': 'Branch nếu họ quay vào.',
  'Branch now.': 'Branch ngay.',
  'Branch out.': 'Branch ra.',
  "Branch, don't force.": 'Branch, đừng force.',
  'Branch, then settle.': 'Branch, rồi ổn định.',
  'Branch.': 'Branch.',
  'Bridge diagonal.': 'Bridge chéo.',
  'Bridge diagonally into the frame.': 'Bridge chéo vào frame.',
  'Bridge diagonally.': 'Bridge chéo.',
  'Bridge, then shrimp.': 'Bridge, rồi shrimp.',
  'Bump hard, angle wide.': 'Bump mạnh, góc rộng.',
  'Catch the far leg.': 'Bắt chân xa.',
  'Chest drives.': 'Ngực lái.',
  'Chest floating.': 'Ngực nổi.',
  'Chest glued to back.': 'Ngực dính lưng.',
  'Chest glued.': 'Ngực dính.',
  'Chest on back.': 'Ngực trên lưng.',
  'Chin in, then hands.': 'Cằm vào, rồi tay.',
  'Chin push.': 'Đẩy cằm.',
  'Chin strap, angle, then finish.': 'Chin strap, góc, rồi finish.',
  'Chin tuck.': 'Cằm gập.',
  'Circle fast.': 'Vòng nhanh.',
  'Clamp the heel.': 'Kẹp gót.',
  'Clamp the hips.': 'Kẹp hông.',
  'Clear the foot.': 'Giải phóng chân.',
  'Clear the knee.': 'Giải phóng gối.',
  'Close the space.': 'Đóng khoảng trống.',
  'Control before finish.': 'Kiểm soát trước finish.',
  'Control first, finish second.': 'Kiểm soát trước, finish sau.',
  'Control first.': 'Kiểm soát trước.',
  'Control then branch.': 'Kiểm soát rồi branch.',
  'Crossface hard.': 'Crossface mạnh.',
  'Crossface, hip, knee.': 'Crossface, hông, gối.',
  'Cuff the wrist.': 'Khóa cổ tay.',
  'Cup the elbow.': 'Đỡ khuỷu.',
  'Deep penetration.': 'Penetration sâu.',
  'Diagonal bridge.': 'Bridge chéo.',
  'Diagonal shoulder.': 'Vai chéo.',
  'Drag hips.': 'Kéo hông.',
  'Drive through the shoulder.': 'Lái qua vai.',
  'Drive through.': 'Lái qua.',
  'Drop your weight.': 'Thả trọng lượng.',
  'Ear to ear.': 'Tai kề tai.',
  'Elbow close.': 'Khuỷu khép.',
  'Elbow down.': 'Khuỷu xuống.',
  'Elbow first.': 'Khuỷu trước.',
  'Elbow in, knee in.': 'Khuỷu vào, gối vào.',
  'Elbow in, then move.': 'Khuỷu vào, rồi di chuyển.',
  'Elbow in.': 'Khuỷu vào.',
  'Elbow low.': 'Khuỷu thấp.',
  'Elbow out, shoulder in danger.': 'Khuỷu ra, vai nguy hiểm.',
  'Elbow post.': 'Post khuỷu.',
  'Elbow tight.': 'Khuỷu chặt.',
  'Elbow-knee.': 'Khuỷu-gối.',
  'Far hip grip': 'Grip hông xa',
  'Find a post.': 'Tìm post.',
  'Find heel.': 'Tìm gót.',
  'Finish or branch.': 'Finish hoặc branch.',
  'Flat then turn.': 'Phẳng rồi xoay.',
  'Foot active.': 'Chân sống.',
  'Forcing a bad finish.': 'Force finish xấu.',
  'Forcing one lane.': 'Force một lane.',
  'Frame and scoot.': 'Frame và scoot.',
  'Frame first.': 'Frame trước.',
  'Frame strong.': 'Frame mạnh.',
  'Frame the shoulders.': 'Frame vai.',
  'Frame, bridge, knee in.': 'Frame, bridge, gối vào.',
  'Frame, bridge, knee.': 'Frame, bridge, gối.',
  'Frame, shrimp, elbow in.': 'Frame, shrimp, khuỷu vào.',
  'Free knee.': 'Gối tự do.',
  'Glue head.': 'Dán đầu.',
  'Granby now.': 'Granby ngay.',
  'Grip the far hip.': 'Grip hông xa.',
  'Hands blocked, knees pinned.': 'Tay bị chặn, gối bị pin.',
  'Hands close.': 'Tay khép.',
  'Hands first, spin second.': 'Tay trước, spin sau.',
  'Hands first, turn second.': 'Tay trước, xoay sau.',
  'Hands on wrist.': 'Tay lên cổ tay.',
  'Hands to neck.': 'Tay lên cổ.',
  'Hands, hook, head, turn.': 'Tay, hook, đầu, xoay.',
  'Head blocks turn-in.': 'Đầu chặn quay vào.',
  'Head blocks.': 'Đầu chặn.',
  'Head close.': 'Đầu gần.',
  'Head down.': 'Đầu xuống.',
  'Head first.': 'Đầu trước.',
  'Head off line.': 'Đầu lệch line.',
  'Head out.': 'Đầu ra.',
  'Head post.': 'Post đầu.',
  'Head safe.': 'Đầu an toàn.',
  'Head short.': 'Đầu ngắn.',
  'Head tight.': 'Đầu chặt.',
  'Head, hand, hip, hook.': 'Đầu, tay, hông, hook.',
  'Head, hand, knee, foot.': 'Đầu, tay, gối, chân.',
  'Head, hip, elbow, knee.': 'Đầu, hông, khuỷu, gối.',
  'Head, hip, foot, branch.': 'Đầu, hông, chân, branch.',
  'Head, staple, switch.': 'Đầu, staple, switch.',
  'Heavy leg.': 'Chân nặng.',
  'Heavy overhook.': 'Overhook nặng.',
  'Heavy shoulder.': 'Vai nặng.',
  'Heavy spiral.': 'Spiral nặng.',
  'Heel hidden, knee free, then move.': 'Gót ẩn, gối tự do, rồi di chuyển.',
  'Heel hidden, knee line free.': 'Gót ẩn, đường gối tự do.',
  'Heel locked.': 'Gót khóa.',
  'Heel to the ground.': 'Gót xuống đất.',
  'Heist high.': 'Vươn cao.',
  'Help the knee.': 'Giúp gối.',
  'Hide the heel.': 'Giấu gót.',
  'Hip block.': 'Block hông.',
  'Hip bump swing': 'Hip bump swing',
  'Hip rotation available.': 'Xoay hông khả dụng.',
  'Hip tight.': 'Hông chặt.',
  'Hips do the work.': 'Hông làm việc.',
  'Hips down.': 'Hông xuống.',
  'Hips first.': 'Hông trước.',
  'Hips low.': 'Hông thấp.',
  'Hips out first.': 'Hông ra trước.',
  'Hips through.': 'Hông qua.',
  'Hips to mat.': 'Hông xuống thảm.',
  'Hips under shoulders.': 'Hông dưới vai.',
  'Hips up, chest in.': 'Hông lên, ngực vào.',
  'Hook active, sleeve pulls.': 'Hook sống, sleeve kéo.',
  'Hook and rotate.': 'Hook và xoay.',
  'Hook deep.': 'Hook sâu.',
  'Hook first.': 'Hook trước.',
  'Hook in.': 'Hook vào.',
  'Hook over the thigh.': 'Hook qua đùi.',
  'Hook the far knee.': 'Hook gối xa.',
  'Hooks pull.': 'Hook kéo.',
  'Invert and scoot.': 'Invert và scoot.',
  'Invert safety': 'An toàn khi invert',
  'Keep feet in front.': 'Giữ chân trước.',
  'Keep head and chest heavy.': 'Giữ đầu và ngực nặng.',
  'Keep the knee up.': 'Giữ gối lên.',
  'Keep them away.': 'Giữ chúng xa.',
  'Keep them off-balance.': 'Giữ họ mất thăng bằng.',
  'Kill the grips.': 'Diệt grip.',
  'Kill the hooks.': 'Diệt hook.',
  'Knee first.': 'Gối trước.',
  'Knee high.': 'Gối cao.',
  'Knee in the pit.': 'Gối trong khoeo.',
  'Knee in.': 'Gối vào.',
  'Knee line first.': 'Đường gối trước.',
  'Knee over shoulder.': 'Gối qua vai.',
  'Knee passes, then settle.': 'Gối qua, rồi ổn định.',
  'Knee through.': 'Gối qua.',
  'Knee to hip.': 'Gối vào hông.',
  'Knees in.': 'Gối vào.',
  'Knees to chest.': 'Gối lên ngực.',
  'Land and settle.': 'Tiếp đất và ổn định.',
  'Leg over the neck.': 'Chân qua cổ.',
  'Lock the hands tight.': 'Khóa tay chặt.',
  'Lock the hips.': 'Khóa hông.',
  'Look at the floor.': 'Nhìn xuống thảm.',
  'Low and diagonal.': 'Thấp và chéo.',
  'Low base.': 'Base thấp.',
  'Low cut.': 'Cut thấp.',
  'Low hips.': 'Hông thấp.',
  'Low lock.': 'Lock thấp.',
  'Mount stays.': 'Giữ mount.',
  'Move first.': 'Di chuyển trước.',
  'No bench press.': 'Không bench press.',
  'No daylight.': 'Không ánh sáng.',
  'Nose over knees.': 'Mũi qua gối.',
  'One layer.': 'Một lớp.',
  'Open the path.': 'Mở đường.',
  'Pin first.': 'Pin trước.',
  'Pin heel.': 'Pin gót.',
  'Pin the heel.': 'Pin gót.',
  'Pin the hip.': 'Pin hông.',
  'Pin the thigh.': 'Pin đùi.',
  'Plan first.': 'Kế hoạch trước.',
  'Post and sit.': 'Post và ngồi.',
  'Pressure then switch.': 'Pressure rồi switch.',
  'Pry deep thigh.': 'Cậy đùi sâu.',
  'Pull yourself under.': 'Kéo mình xuống dưới.',
  'Pull, land, settle.': 'Kéo, đáp, ổn định.',
  'Pummel deep.': 'Pummel sâu.',
  'Push with underhook.': 'Đẩy bằng underhook.',
  'Radius on Achilles.': 'Radius trên Achilles.',
  'Reach deep.': 'Với sâu.',
  'Reach for the hip.': 'Với hông.',
  'Reconnect elbow to knee.': 'Kết nối lại khuỷu-gối.',
  'Recover elbow-knee.': 'Phục hồi khuỷu-gối.',
  'Recover knee to elbow.': 'Phục hồi gối-khuỷu.',
  'Remove slack.': 'Xóa slack.',
  'Reset early.': 'Reset sớm.',
  'Reset first.': 'Reset trước.',
  'Reset to front headlock.': 'Reset về front headlock.',
  'Return, then pin.': 'Quay lại, rồi pin.',
  'Roll on shoulders.': 'Lăn trên vai.',
  'Safe side down.': 'Side an toàn xuống.',
  'Safe side, then exit.': 'Side an toàn, rồi thoát.',
  'Safe side.': 'Side an toàn.',
  'Scoop the leg.': 'Scoop chân.',
  'Scoot away.': 'Scoot ra.',
  'Scoot out.': 'Scoot ra.',
  'Scoot to the back.': 'Scoot ra sau.',
  'Seatbelt first.': 'Seatbelt trước.',
  'Seatbelt, hooks, then choke.': 'Seatbelt, hook, rồi choke.',
  'Second leg.': 'Chân thứ hai.',
  'Settle Side Control.': 'Ổn định side control.',
  'Settle before release.': 'Ổn định trước khi thả.',
  'Settle immediately.': 'Ổn định ngay.',
  'Settle now.': 'Ổn định ngay.',
  'Settle side control.': 'Ổn định side control.',
  'Settle.': 'Ổn định.',
  'Shelf and pin.': 'Shelf và pin.',
  'Shelf the leg.': 'Shelf chân.',
  'Shield high.': 'Shield cao.',
  'Shield up.': 'Shield lên.',
  'Short head, tall hips.': 'Đầu ngắn, hông cao.',
  'Shoulders first.': 'Vai trước.',
  'Shoulders locked.': 'Vai khóa.',
  'Shoulders to floor.': 'Vai xuống sàn.',
  'Shrimp away.': 'Shrimp ra.',
  'Sit up fast.': 'Ngồi dậy nhanh.',
  'Slack out.': 'Hết slack.',
  'Slip behind.': 'Trượt ra sau.',
  'Slow, then decide.': 'Chậm, rồi quyết định.',
  'Slow.': 'Chậm.',
  'Space first.': 'Khoảng trống trước.',
  'Spiral the shoulder.': 'Spiral vai.',
  'Squeeze only after slack is gone.': 'Squeeze sau khi hết slack.',
  'Squeeze then break.': 'Squeeze rồi break.',
  'Stabilize side control.': 'Stabilize side control.',
  'Stabilize.': 'Stabilize.',
  'Staple the near leg.': 'Staple chân gần.',
  'Staple.': 'Staple.',
  'Staying square.': 'Giữ square.',
  'Step and angle.': 'Bước và góc.',
  'Stick to the back.': 'Dính vào lưng.',
  'Sticky feet.': 'Chân dính.',
  'Stop spin.': 'Dừng spin.',
  'Strip and circle.': 'Strip và vòng.',
  'Strong chin strap.': 'Chin strap mạnh.',
  'Switch to leg drag if needed.': 'Chuyển sang leg drag nếu cần.',
  'Tap earlier, reduce force.': 'Tap sớm hơn, giảm lực.',
  'Tight hips.': 'Hông chặt.',
  'Tighten the wedge.': 'Siết wedge.',
  'Tripod up.': 'Tripod lên.',
  'Turn to guard or turtle.': 'Xoay về guard hoặc turtle.',
  'Turn to side control or half guard.': 'Xoay về side control hoặc half guard.',
  'Turn to side or half guard.': 'Xoay về side hoặc half guard.',
  'Turn to the lock.': 'Xoay vào lock.',
  'Turn to turtle or guard.': 'Xoay về turtle hoặc guard.',
  'Turn with a plan.': 'Xoay có kế hoạch.',
  'Turn with connection.': 'Xoay có kết nối.',
  'Turn with frames.': 'Xoay có frame.',
  'Under chin.': 'Dưới cằm.',
  'Wedge the outside foot.': 'Wedge chân ngoài.',
  'Weight through knee.': 'Trọng lượng qua gối.',
  'Win hands.': 'Thắng tay.',
  'Win head.': 'Thắng đầu.',
  'Win the choking hand.': 'Thắng tay choke.',
  'Win the snap or front headlock.': 'Thắng snap hoặc front headlock.',
  'Wrist + hip.': 'Cổ tay + hông.',
  'Wrist first.': 'Cổ tay trước.',
  'Wrist, elbow, angle.': 'Cổ tay, khuỷu, góc.',
};

// Now apply to microDetailSystems.ts
let c = fs.readFileSync('src/data/microDetailSystems.ts', 'utf8');
let count = 0;
let skipped = 0;

for (const [en, vi] of Object.entries(enToVi)) {
  if (en === vi) {
    skipped++;
    continue; // identity mapping, skip
  }
  // Escape special regex chars
  const escaped = en.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
  const regex = new RegExp(`(lt\\()('${escaped}'(?:,\\s*)('${escaped}'))`, 'g');
  const newC = c.replace(regex, (match, p1, p2) => {
    count++;
    return `lt('${vi}${p2.substring(p2.indexOf("',"))}`;
  });
  if (newC !== c) {
    c = newC;
  }
}

fs.writeFileSync('src/data/microDetailSystems.ts', c, 'utf8');
console.log(`\nApplied ${count} translations. Skipped ${skipped} identity mappings.`);
