import fs from 'fs'

const filePath = 'src/data/blackbeltDetails.ts'
let content = fs.readFileSync(filePath, 'utf8')

// Complete mapping of English → Vietnamese for all 450 unique identical phrases
const mapping = {
  // === Section headers with "/" ===
  'Control / Entry': 'Kiểm soát / Vào',
  'Isolation / Alignment': 'Cô lập / Căn chỉnh',
  'Finish / Safety': 'Kết thúc / An toàn',
  'Angle / Pressure': 'Góc / Áp lực',
  'Angle / Isolation': 'Góc / Cô lập',
  'Angle / Shift': 'Góc / Xoay',
  'Isolation / Pinch': 'Cô lập / Kẹp',
  'Isolation / Ride': 'Cô lập / Ride',
  'Control / Stabilization': 'Kiểm soát / Ổn định',
  'Control / Mobility': 'Kiểm soát / Di chuyển',
  'Branch / Finish': 'Nhánh / Kết thúc',
  'Finish / Branch': 'Kết thúc / Nhánh',
  'Finish / Compression': 'Kết thúc / Nén',
  'Finish / Torque': 'Kết thúc / Torque',
  'Finish / Sweep': 'Kết thúc / Quét',
  'Exit / Safety': 'Thoát / An toàn',
  'Entry / Ankle Line': 'Vào / Ankle Line',
  'Hip / Hook Control': 'Hông / Hook Control',
  'Re-guard / Stabilization': 'Re-guard / Ổn định',
  'Recovery / Stance': 'Hồi phục / Tư thế',
  'Pin Stabilization': 'Ổn định Pin',
  'Pass Stabilization': 'Ổn định Pass',
  'Hip Stability': 'Ổn định Hông',
  'Upper Body Isolation': 'Cô lập Thân trên',
  'Chest Connection': 'Kết nối Ngực',
  'Shoulder Control': 'Kiểm soát Vai',
  'Hip Control': 'Kiểm soát Hông',
  'Hip & Hook Control': 'Kiểm soát Hông & Hook',
  'Hip Escape / Gap': 'Hip Escape / Khe hở',
  'Leg Extraction': 'Rút Chân',
  'Leg Isolation': 'Cô lập Chân',
  'Knee Line Control': 'Kiểm soát Đường gối',
  'Heel Exposure': 'Lộ Gót',
  'Wrist Clamp': 'Kẹp Cổ tay',
  'Figure-four lock': 'Khóa Figure-four',
  Locking: 'Khóa',
  'Locking / Angle': 'Khóa / Góc',
  Compression: 'Nén',
  Stabilization: 'Ổn định',
  'Secondary Branches': 'Nhánh phụ',
  'Base / Frame': 'Nền / Frame',
  'Hip Angle': 'Góc Hông',
  'Elbow / Shoulder Isolation': 'Cô lập Khuỷu / Vai',
  Recognize: 'Nhận diện',
  'Free Knee Line': 'Giải phóng Đường gối',
  'Isolation & Finish': 'Cô lập & Kết thúc',
  'Isolation / Posture': 'Cô lập / Posture',
  Entry: 'Vào',
  Angle: 'Góc',
  Weight: 'Trọng lượng',
  'Entry / Isolation': 'Vào / Cô lập',

  // === "xxx first." cues ===
  'Wrist first.': 'Cổ tay trước.',
  'Angle first.': 'Góc trước.',
  'Elbow first.': 'Khuỷu trước.',
  'Hook first.': 'Hook trước.',
  'Knee line first.': 'Đường gối trước.',
  'Heel first.': 'Gót trước.',
  'Walk first.': 'Walk trước.',
  'Mount first.': 'Mount trước.',
  'Across first.': 'Qua trước.',
  'Arm across first.': 'Tay qua trước.',
  'Shrimp first.': 'Shrimp trước.',
  'Settle first.': 'Ổn định trước.',
  'Stop first.': 'Dừng trước.',
  'Posture first.': 'Posture trước.',
  'Align first.': 'Căn chỉnh trước.',
  'Hands first.': 'Tay trước.',
  'Kill hook first.': 'Triệt hook trước.',
  'Hips out first.': 'Hông ra trước.',
  'Knee line first': 'Đường gối trước',
  'Angle before squeeze': 'Góc trước squeeze',
  'Angle before squeeze.': 'Góc trước squeeze.',
  'Elbow before squeeze': 'Khuỷu trước squeeze',
  'Thumb up before hips.': 'Ngón cái lên trước hông.',
  'Win hand fight first.': 'Thắng hand fight trước.',

  // === "xxx glued." / "xxx heavy." / "xxx tight." etc ===
  'Chest glued.': 'Ngực dính.',
  'Chest glued to back': 'Ngực dính lưng',
  'Chest glued to spine': 'Ngực dính cột sống',
  'Head glued.': 'Đầu dính.',
  'Ear glued.': 'Tai dính.',
  'Elbow tight.': 'Khuỷu chặt.',
  'Knee tight.': 'Gối chặt.',
  'Triangle tight.': 'Triangle chặt.',
  'Figure-four tight.': 'Figure-four chặt.',
  'Lock tight.': 'Khóa chặt.',
  'Chest heavy.': 'Ngực nặng.',
  'Heavy hips.': 'Hông nặng.',
  'Stay heavy.': 'Giữ nặng.',
  'Toe to ceiling.': 'Ngón chân lên trần.',
  'Deep shin.': 'Shin sâu.',
  'Deep pocket.': 'Pocket sâu.',
  'Deep.': 'Sâu.',
  'Lock deep.': 'Khóa sâu.',
  'Slow pressure.': 'Áp lực chậm.',
  'Slow hips.': 'Hông chậm.',
  'Slow finish.': 'Kết thúc chậm.',
  'Slow rotation.': 'Xoay chậm.',
  'Slow arch.': 'Arch chậm.',
  'Slow hip extension': 'Extension hông chậm',
  'Slow shoulder pressure': 'Áp lực vai chậm',
  'Torque slow.': 'Torque chậm.',
  'Squeeze hard.': 'Squeeze mạnh.',
  'Squeeze knees.': 'Squeeze gối.',
  'Short choke branch': 'Nhánh choke ngắn',

  // === "No xxx." cues ===
  'No gap.': 'Không khe hở.',
  'No space.': 'Không khoảng trống.',
  'No space means no rotation.': 'Không khoảng trống = không xoay.',
  'No space means no escape.': 'Không khoảng trống = không thoát.',
  'No arm escape.': 'Không thoát tay.',
  'No blind spin.': 'Không spin mù.',
  'No blind spin': 'Không spin mù',
  'No turn in.': 'Không quay vào.',
  'No knee escape.': 'Không thoát gối.',
  'No elbow space.': 'Không khoảng khuỷu.',

  // === "Kill xxx." / "Stop xxx." / "Block xxx." ===
  'Kill bridge.': 'Triệt bridge.',
  'Kill rotation.': 'Triệt xoay.',
  'Block elbow.': 'Chặn khuỷu.',
  'Block far hip.': 'Chặn hông xa.',
  'Block the hips.': 'Chặn hông.',
  'Stops roll escape.': 'Chặn roll thoát.',
  'Prevents back escape.': 'Ngăn thoát lưng.',
  'Prevents counter-hook.': 'Ngăn counter-hook.',
  'Prevents face squeeze.': 'Ngăn squeeze mặt.',
  'Prevents heel slip.': 'Ngăn trượt gót.',

  // === "xxx in." / "xxx out." / "xxx down." / "xxx up." ===
  'Knees in.': 'Gối vào.',
  'Heels in.': 'Gót vào.',
  'Hook in.': 'Hook vào.',
  'Hip out.': 'Hông ra.',
  'Shift out.': 'Xoay ra.',
  'Slack out.': 'Hết slack.',
  'Hands up.': 'Tay lên.',
  'Head up.': 'Đầu lên.',
  'Hips up.': 'Hông lên.',
  'Frames up.': 'Frame lên.',
  'Post wide.': 'Post rộng.',
  'Head down.': 'Đầu xuống.',
  'Hips down.': 'Hông xuống.',
  'Hip down.': 'Hông xuống.',
  'Chin down.': 'Cằm xuống.',
  'Base hands.': 'Tay base.',
  'Extend arm.': 'Duỗi tay.',
  'Extend hips.': 'Duỗi hông.',
  'Pull elbow.': 'Kéo khuỷu.',
  'Peel hands.': 'Peel tay.',
  'Peel wrist.': 'Peel cổ tay.',
  'Walk first.': 'Walk trước.',
  'Rotate hips.': 'Xoay hông.',
  'Hips turn.': 'Hông xoay.',
  'Hips lift.': 'Hông nâng.',
  'Hip drive.': 'Hông đẩy.',
  'Hip escape.': 'Hip escape.',
  'Hip angle': 'Góc hông',
  'Hip extension': 'Extension hông',
  'Hips slow.': 'Hông chậm.',
  'Hips up, knees in.': 'Hông lên, gối vào.',
  'Hips out first.': 'Hông ra trước.',
  'Hips walk out': 'Hông walk ra',
  'Hips angle outside': 'Hông góc ngoài',
  'Hips are outside and posture is tall.': 'Hông ngoài và posture cao.',
  'Hips close shoulder': 'Hông đóng vai',
  'Hips to shoulder.': 'Hông vào vai.',
  'Hips heavy on pelvis': 'Hông nặng trên xương chậu',
  'Hips up.': 'Hông lên.',
  'Hips down.': 'Hông xuống.',
  'Knee line': 'Đường gối',
  'Knee line clamp': 'Kẹp đường gối',
  'Knee line is isolated and heel is in pocket.': 'Đường gối bị cô lập và gót trong pocket.',
  'Knee beside head': 'Gối cạnh đầu',
  'Knee near ear.': 'Gối gần tai.',
  'Knee blocks hip': 'Gối chặn hông',
  'Knee kills hook': 'Gối triệt hook',
  'Knee clear': 'Gối thoát',
  'Knee in.': 'Gối vào.',
  'Clear knee.': 'Thoát gối.',
  'Clear second leg': 'Thoát chân thứ hai',
  'Clear second leg.': 'Thoát chân thứ hai.',
  'Second leg.': 'Chân thứ hai.',
  'Second leg controls posture': 'Chân thứ hai kiểm soát posture',
  'Free knee.': 'Gối tự do.',
  'Knee shearing pressure': 'Áp lực cắt gối',
  'Knee to hip.': 'Gối vào hông.',
  'Knee to elbow.': 'Gối vào khuỷu.',

  // === "Close xxx." ===
  'Close elbow.': 'Khép khuỷu.',
  'Close neck gap.': 'Đóng khe cổ.',
  'Close space inward.': 'Đóng khoảng vào trong.',
  'Close the gap.': 'Đóng khe hở.',

  // === "Hip xxx" / "Head xxx" / "Elbow xxx" ===
  'Hip Angle': 'Góc Hông',
  'Hip angle': 'Góc hông',
  'Hip angle removes the roll path and sets shoulder pressure.': 'Góc hông loại bỏ đường roll và tạo áp lực vai.',
  'Hip angle to trapped arm': 'Góc hông vào tay bị kẹp',
  'Hip rotation torque': 'Torque xoay hông',
  'Hip rotation / Angle': 'Xoay hông / Góc',
  'Hip shift outside': 'Xoay hông ra ngoài',
  'Hip rotates shoulder': 'Hông xoay vai',
  'Hip, not arm.': 'Hông, không tay.',
  'Head offset': 'Đầu lệch',
  'Head off center.': 'Đầu lệch tâm.',
  'Offset head.': 'Lệch đầu.',
  'Head beside head': 'Đầu cạnh đầu',
  'Head beside.': 'Đầu cạnh.',
  'Head blocks elbow': 'Đầu chặn khuỷu',
  'Head blocks elbow.': 'Đầu chặn khuỷu.',
  'Head blocks turn': 'Đầu chặn xoay',
  'Head clamp': 'Kẹp đầu',
  'Head clamp and chest-to-back.': 'Kẹp đầu và chest-to-back.',
  'Head clamp pressure': 'Áp lực kẹp đầu',
  'Head floats outside.': 'Đầu nổi ra ngoài.',
  'Head too high.': 'Đầu quá cao.',
  'Head up posture': 'Đầu lên posture',
  'Elbow first.': 'Khuỷu trước.',
  'Elbow closes ribs': 'Khuỷu khép sườn',
  'Elbow flares out.': 'Khuỷu mở ra.',
  'Elbow glued to ribs.': 'Khuỷu dính sườn.',
  'Elbow is above hip line.': 'Khuỷu trên đường hông.',
  'Elbow is centered under chin.': 'Khuỷu giữa dưới cằm.',
  'Elbow off ribs': 'Khuỷu khỏi sườn',
  'Elbow off ribs.': 'Khuỷu khỏi sườn.',
  'Elbow outside.': 'Khuỷu ngoài.',
  'Elbow too shallow.': 'Khuỷu quá nông.',
  'Elbow to ribs.': 'Khuỷu vào sườn.',
  'Elbow under chin line.': 'Khuỷu dưới đường cằm.',
  'Elbow Line': 'Đường khuỷu',

  // === Angle-related cues ===
  'Angle cut.': 'Góc cắt.',
  'Cut angle.': 'Cắt góc.',
  'Cut the angle.': 'Cắt góc.',
  'Create angle.': 'Tạo góc.',
  'Angle outside.': 'Góc ngoài.',
  'Angle, then pressure.': 'Góc, rồi áp lực.',
  'Angle is cut and foot is hidden.': 'Góc cắt và chân giấu.',
  'Square angle or foot exposed.': 'Góc vuông hoặc chân lộ.',
  'Safe turning angle': 'Góc xoay an toàn',
  'The angle lines the thigh with the neck and removes shoulder space.': 'Góc đưa đùi vào cổ và loại bỏ khoảng vai.',
  'Angle / Isolation': 'Góc / Cô lập',
  'Angle / Pressure': 'Góc / Áp lực',
  'Angle / Shift': 'Góc / Xoay',
  'Sit tall after angle.': 'Ngồi cao sau góc.',
  'Posture tall.': 'Posture cao.',
  'Move hips outside before pressure.': 'Di chuyển hông ra trước áp lực.',
  'Dismount to the side and lower hips before squeezing.': 'Xuống một bên và hạ hông trước squeeze.',
  'Squeeze knees after angle, branch if posture returns.': 'Squeeze gối sau góc, branch nếu posture về.',
  'Pinch, then lift.': 'Kẹp, rồi nâng.',
  'Pin, then release.': 'Pin, rồi thả.',
  'Release after pin': 'Thả sau pin',
  'Release on tap.': 'Thả khi tap.',
  'Tap means stop.': 'Tap = dừng.',
  'Tap comes before force spikes.': 'Tap đến trước khi lực tăng mạnh.',
  'Lock hips.': 'Khóa hông.',
  'Low hip lock': 'Khóa hông thấp',
  'Kill rotation.': 'Triệt xoay.',
  'Catch the heel.': 'Bắt gót.',
  'Hide heel': 'Giấu gót',
  'Hide heel.': 'Giấu gót.',
  'Hide the foot.': 'Giấu chân.',
  'Foot hidden.': 'Chân giấu.',
  'Foot hidden behind knee': 'Chân giấu sau gối',
  'Foot is locked under armpit.': 'Chân khóa dưới nách.',
  'Ankle line.': 'Ankle line.',
  'Ankle is in pocket and knees are pinching.': 'Ankle trong pocket và gối kẹp.',
  'Heel in elbow pocket': 'Gót trong pocket khuỷu',
  'Hidden foot keeps the triangle closed without ankle exposure.': 'Chân giấu giữ triangle đóng không lộ ankle.',
  'Isolates the heel lever.': 'Cô lập lever gót.',
  'Fixes the lever.': 'Cố định lever.',
  'Wrist control keeps the shoulder lever connected.': 'Wrist control giữ lever vai kết nối.',

  // === Full technique instructions ===
  'Armbar: isolate shoulder, keep elbow above hip line, then extend slowly.': 'Armbar: cô lập vai, giữ khuỷu trên đường hông, rồi duỗi chậm.',
  'Kimura: wrist first, elbow off ribs, hip rotation.': 'Kimura: cổ tay trước, khuỷu khỏi sườn, xoay hông.',
  'Guillotine: chin strap, elbow line, hip angle.': 'Guillotine: chin strap, đường khuỷu, góc hông.',
  'Omoplata: shoulder clamp, wrist control, hip angle, slow shoulder pressure.': 'Omoplata: kẹp vai, wrist control, góc hông, áp lực vai chậm.',
  'Straight ankle: ankle line, elbow clamp, knee line, slow hips.': 'Straight ankle: ankle line, kẹp khuỷu, đường gối, hông chậm.',
  'Triangle: one shoulder in, one shoulder out, posture broken, angle cut before squeeze.': 'Triangle: một vai trong, một vai ngoài, posture gãy, góc cắt trước squeeze.',

  // === Shoulder / Arm related ===
  'Shoulder Clamp': 'Kẹp Vai',
  'Shoulder Control': 'Kiểm soát Vai',
  'Shoulder isolation': 'Cô lập vai',
  'Shoulder isolation turns guard into a lever instead of a scramble.': 'Cô lập vai biến guard thành lever thay vì scramble.',
  'Shoulder line': 'Đường vai',
  'Shoulder line clamp': 'Kẹp đường vai',
  'Shoulder line denial': 'Chặn đường vai',
  'Shoulder split.': 'Tách vai.',
  'Shoulder trapped.': 'Vai kẹt.',
  'Shoulder and wrist are trapped.': 'Vai và cổ tay kẹt.',
  'Shoulder-head clamp': 'Kẹp vai-đầu',
  'Shoulder-neck clamp': 'Kẹp vai-cổ',
  'Shoulders to mat.': 'Vai xuống thảm.',
  'Pin the shoulder.': 'Pin vai.',
  'Frame the shoulder.': 'Frame vai.',
  'Clamp shoulder.': 'Kẹp vai.',
  'Shin clamps shoulder': 'Shin kẹp vai',
  'Shin over shoulder.': 'Shin qua vai.',
  'Shin across neck': 'Shin qua cổ',
  'Shin across.': 'Shin qua.',
  'Shin horizontal.': 'Shin ngang.',
  'Trap the shoulder before sitting up.': 'Kẹp vai trước khi ngồi lên.',
  'Diagonal shoulder': 'Vai chéo',
  'Diagonal shoulder.': 'Vai chéo.',
  'Diagonal post.': 'Post chéo.',

  // === Wrist / Hand related ===
  'Wrist control': 'Wrist control',
  'Wrist control.': 'Wrist control.',
  'Wrist Clamp': 'Kẹp Cổ tay',
  'Wrist pin': 'Pin cổ tay',
  'Wrist first.': 'Cổ tay trước.',
  'Wrist high.': 'Cổ tay cao.',
  'Wrist across face.': 'Cổ tay qua mặt.',
  'Wrist blade is deep.': 'Sống cổ tay sâu.',
  'Wrist stays pinned.': 'Cổ tay giữ pin.',
  'Wrist under chin.': 'Cổ tay dưới cằm.',
  'Wrist under chin, elbow to ribs, high elbow rotation or hip angle.': 'Cổ tay dưới cằm, khuỷu vào sườn, xoay khuỷu cao hoặc góc hông.',
  'Pin wrist.': 'Pin cổ tay.',
  'Pin wrist, separate elbow, rotate hips instead of arms for the finish.': 'Pin cổ tay, tách khuỷu, xoay hông thay vì tay cho finish.',
  'Own wrist.': 'Giữ cổ tay.',
  'Hand owns wrist': 'Tay giữ cổ tay',
  'Hands own wrist': 'Tay giữ cổ tay',
  'Hand moves past the shoulder line.': 'Tay qua khỏi đường vai.',
  'Hand blocks far hip': 'Tay chặn hông xa',
  'Hand frames': 'Frame tay',
  'Hands base out': 'Tay base ra',
  'Hands break posture': 'Tay phá posture',
  'Hands low.': 'Tay thấp.',
  'Support hand wins wrist': 'Tay support thắng cổ tay',
  'Control hands': 'Kiểm soát tay',
  'Control the hand.': 'Kiểm soát tay.',
  'Trap the hand.': 'Kẹp tay.',
  'Keep distance.': 'Giữ khoảng cách.',
  'Keep mount.': 'Giữ mount.',
  'Keep pressure.': 'Giữ áp lực.',
  'Keep shoulders off mat.': 'Giữ vai khỏi thảm.',
  'Keep wrist blade under jaw, head glued, and finish without chasing full figure-four.': 'Giữ sống cổ tay dưới hàm, đầu dính, và finish không chase full figure-four.',
  'Win hands, align elbow, remove slack, then squeeze with chest expansion.': 'Thắng tay, căn khuỷu, bỏ slack, rồi squeeze với expansion ngực.',
  'Win wrist, slide under jaw.': 'Thắng cổ tay, trượt dưới hàm.',
  'Pin head inward to stop turn-in.': 'Pin đầu vào trong để chặn turn-in.',

  // === Body connection cues ===
  'Chest to back': 'Ngực vào lưng',
  'Chest to chest.': 'Ngực vào ngực.',
  'Chest to hip.': 'Ngực vào hông.',
  'Chest to near hip': 'Ngực vào hông gần',
  'Chest follows.': 'Ngực theo.',
  'Chest follows their upper back.': 'Ngực theo lưng trên.',
  'Chest expansion': 'Expansion ngực',
  'Chest pins.': 'Ngực pin.',
  'Chest rises to posture': 'Ngực lên posture',
  'Chest-to-back clamp': 'Kẹp chest-to-back',
  'Chest glued': 'Ngực dính',
  'Ear to ear.': 'Tai kề tai.',
  'Ear to head.': 'Tai kề đầu.',
  'Glue to back.': 'Dính vào lưng.',
  'Body squeeze.': 'Squeeze thân.',
  'Body is at 90 degrees to opponent.': 'Thân vuông góc 90° với đối thủ.',
  'Both legs own posture.': 'Cả hai chân giữ posture.',
  'Pinch, then lift.': 'Kẹp, rồi nâng.',
  'Pinch the neck.': 'Kẹp cổ.',
  'Pinch the neck.': 'Kẹp cổ.',
  'Knees pinch neck': 'Gối kẹp cổ',
  'Knees pinch elbow line': 'Gối kẹp đường khuỷu',
  'Knees pinch.': 'Gối kẹp.',
  'Knees close.': 'Gối khép.',
  'Knees close shoulder line': 'Gối khép đường vai',
  'Knees finish the strangle; arms only maintain posture.': 'Gối kết thúc strangle; tay chỉ giữ posture.',
  'Knees, not neck pull.': 'Gối, không kéo cổ.',
  'Knees together': 'Gối khép',
  'Knees together finish': 'Kết thúc gối khép',
  'Knees together.': 'Gối khép.',
  'Knees to armpits.': 'Gối vào nách.',
  'Arch slowly using hips, not the back, and look away.': 'Arch chậm bằng hông, không lưng, và nhìn ra.',
  'Arching without rotation.': 'Arch không xoay.',
  'Bridge into neck.': 'Bridge vào cổ.',
  'Break posture.': 'Phá posture.',
  'Break posture while one shoulder remains inside.': 'Phá posture khi một vai trong.',
  'Break posture, clear the arm, cut a 90-degree angle, then squeeze knees together.': 'Phá posture, thoát tay, cắt góc 90°, rồi squeeze gối.',
  'Pull the head down while driving knees together and lifting hips.': 'Kéo đầu xuống trong khi đưa gối vào và nâng hông.',
  'Pulling only the head without hip lift.': 'Chỉ kéo đầu không nâng hông.',
  'Using only arm strength.': 'Chỉ dùng sức tay.',
  'Curling arms first.': 'Curl tay trước.',
  'Spinning without control.': 'Spin không kiểm soát.',
  'Rotate your entire upper body toward their toes, not just your arms.': 'Xoay toàn bộ thân trên về phía ngón chân họ, không chỉ tay.',
  'Rotate your hips and shoulders to move their hand toward their back.': 'Xoay hông và vai để đưa tay họ về lưng.',
  'Rotational body torque': 'Torque xoay thân',
  'Turning into their base.': 'Xoay vào base họ.',
  'Turn away from the free leg.': 'Xoay khỏi chân tự do.',
  'Apply pressure through the hips into their knee line.': 'Áp lực qua hông vào đường gối họ.',
  'Add shoulder pressure slowly or sweep when they roll.': 'Thêm áp lực vai chậm hoặc sweep khi họ roll.',
  'Gradual hip pressure gives defender time to tap and exposes the sweep branch.': 'Áp lực hông từ từ cho defender thời gian tap và mở nhánh sweep.',
  'Tap or sweep appears.': 'Tap hoặc sweep xuất hiện.',
  'Defender hides shoulder or rolls early.': 'Defender giấu vai hoặc roll sớm.',
  'Defender rolls or squares hips.': 'Defender roll hoặc xoay hông vuông.',
  'Defender stands tall.': 'Defender đứng cao.',
  'Defensive hand blocks full lock.': 'Tay phòng thủ chặn khóa đầy đủ.',
  'Posture Break': 'Phá Posture',
  'Posture first.': 'Posture trước.',
  'Posture is broken and shoulder split is clear.': 'Posture gãy và tách vai rõ.',
  'Posture returns or stack begins.': 'Posture về hoặc stack bắt đầu.',
  'Posture tall.': 'Posture cao.',
  'Posture trapped.': 'Posture kẹt.',
  'Post the foot.': 'Post chân.',
  'Face away.': 'Quay mặt đi.',
  'Look into the ear.': 'Nhìn vào tai.',
  'Stiff arms.': 'Tay cứng.',
  'Stay in base.': 'Giữ base.',
  'Stay mobile.': 'Giữ di chuyển.',
  'Watch the secondary leg.': 'Theo dõi chân thứ hai.',
  'Always know where the secondary leg is.': 'Luôn biết chân thứ hai ở đâu.',
  'Weight distribution': 'Phân bố trọng lượng',
  'Low hip lock': 'Khóa hông thấp',
  'Near knee shield': 'Knee shield gần',
  'Grapevine legs': 'Grapevine chân',
  'Grapevine feet.': 'Grapevine chân.',
  'Feet on hips': 'Chân trên hông',
  'Feet to hips.': 'Chân vào hông.',
  'High mount.': 'High mount.',
  'Mount hip clamp': 'Kẹp hông mount',
  'Mount first.': 'Mount trước.',
  'Slack, then chest.': 'Slack, rồi ngực.',
  'Slack, then squeeze.': 'Slack, rồi squeeze.',
  'Slack out.': 'Hết slack.',
  'Removes neck slack.': 'Xóa slack cổ.',
  'Sliding too high.': 'Trượt quá cao.',
  'Squeezing from mount.': 'Squeeze từ mount.',
  'Squeezing jaw or face.': 'Squeeze hàm hoặc mặt.',
  'Space under neck.': 'Khoảng dưới cổ.',
  'Gap behind neck.': 'Khe sau cổ.',
  'Locks head position.': 'Khóa vị trí đầu.',
  'Compresses carotid.': 'Nén động mạch cảnh.',
  'Eliminates airway space.': 'Loại bỏ không gian thở.',
  'Traps carotid.': 'Kẹp động mạch cảnh.',
  'Strangle closes with small squeeze.': 'Strangle đóng với squeeze nhỏ.',
  'One shoulder in and one shoulder out creates the strangle frame.': 'Một vai trong một vai ngoài tạo frame strangle.',
  'One shoulder out.': 'Một vai ngoài.',
  'Opponent face turns red/purple.': 'Mặt đối thủ đỏ/tím.',
  'They stack or rotate thumb down.': 'Họ stack hoặc xoay ngón cái xuống.',
  'Thumb direction reveals the elbow line and stops rotation escape.': 'Hướng ngón cái lộ đường khuỷu và chặn thoát xoay.',
  'Thumb line.': 'Đường ngón cái.',
  'Chin line angle': 'Góc đường cằm',
  'Chin line cleared and hand fight won.': 'Đường cằm thoáng và thắng hand fight.',
  'Chin strap clamp': 'Kẹp chin strap',
  'Chin strap wrist': 'Cổ tay chin strap',
  'Chin strap.': 'Chin strap.',
  'Choking elbow clamp': 'Kẹp khuỷu choke',
  'Underhook high.': 'Underhook cao.',
  'Underhook separation': 'Tách underhook',
  'Crossface pressure': 'Áp lực crossface',
  'Clear the hook.': 'Thoát hook.',
  'Clamp knee line.': 'Kẹp đường gối.',
  'Clamp the shoulder line.': 'Kẹp đường vai.',
  'Control hips.': 'Kiểm soát hông.',
  'Elbow first.': 'Khuỷu trước.',
  'Extend gradually and keep knees pinched.': 'Duỗi từ từ và giữ gối kẹp.',
  'Follow shoulders.': 'Theo vai.',
  'Forearm on ankle line, elbow closed, knees clamp, hips extend slowly.': 'Forearm trên ankle line, khuỷu khép, gối kẹp, hông duỗi chậm.',
  'Hips close shoulder': 'Hông đóng vai',
  'Hips low and angled': 'Hông thấp và góc',
  'Hips under.': 'Hông dưới.',
  'Hooks pull.': 'Hook kéo.',
  'Jerking the back.': 'Giật lưng.',
  'Lock behind head.': 'Khóa sau đầu.',
  'Locking the loop': 'Khóa vòng',
  'Locks head position.': 'Khóa vị trí đầu.',
  'Low base.': 'Base thấp.',
  'No gap.': 'Không khe hở.',
  'No space.': 'Không khoảng trống.',
  'Peel hands.': 'Peel tay.',
  'Peel wrist.': 'Peel cổ tay.',
  'Pin the shoulder.': 'Pin vai.',
  'Pin head inward to stop turn-in.': 'Pin đầu vào trong để chặn turn-in.',
  'Pin wrist, separate elbow, rotate hips instead of arms for the finish.': 'Pin cổ tay, tách khuỷu, xoay hông thay vì tay cho finish.',
  'Pinched knees stop shoulder rotation and make less force necessary.': 'Gối kẹp chặn xoay vai và cần ít lực hơn.',
  'Press into their hip line.': 'Ép vào đường hông họ.',
  'Prevent the escape.': 'Ngăn thoát.',
  'Pull elbow back, then expand chest and close shoulders.': 'Kéo khuỷu về, rồi expansion ngực và khép vai.',
  'Pull slack backward.': 'Kéo slack về sau.',
  'Pull the arm across their centerline.': 'Kéo tay qua centerline họ.',
  'Push their far hip to kill the turn.': 'Đẩy hông xa để triệt xoay.',
  'Release on tap.': 'Thả khi tap.',
  'Rib-to-wrist finish': 'Finish sườn-cổ tay',
  'Ribs to wrist.': 'Sườn vào cổ tay.',
  'Risk of fast pop.': 'Nguy cơ pop nhanh.',
  'Risk of neck crank.': 'Nguy cơ crank cổ.',
  'Safe release': 'Thả an toàn',
  'Safe side.': 'Pha an toàn.',
  'Separate elbow.': 'Tách khuỷu.',
  'Shoulder clamp.': 'Kẹp vai.',
  'Shoulder isolation turns guard into a lever instead of a scramble.': 'Cô lập vai biến guard thành lever thay vì scramble.',
  'Slack, then chest.': 'Slack, rồi ngực.',
  'Slow hip extension': 'Extension hông chậm',
  'Slow pressure.': 'Áp lực chậm.',
  'Stabilization': 'Ổn định',
  'Stop first.': 'Dừng trước.',
  'Support hand wins wrist': 'Tay support thắng cổ tay',
  'Tap comes before force spikes.': 'Tap đến trước khi lực tăng mạnh.',
  'Tap means stop.': 'Tap = dừng.',
  'The angle lines the thigh with the neck and removes shoulder space.': 'Góc đưa đùi vào cổ và loại bỏ khoảng vai.',
  'Toe to ceiling.': 'Ngón chân lên trần.',
  'Torque slow.': 'Torque chậm.',
  'Trap the hand.': 'Kẹp tay.',
  'Trap the shoulder before sitting up.': 'Kẹp vai trước khi ngồi lên.',
  'Triangle is locked and angle is cut.': 'Triangle khóa và góc cắt.',
  'Triangle tight.': 'Triangle chặt.',
  'Turn away from the free leg.': 'Xoay khỏi chân tự do.',
  'Under-arm hand trap': 'Kẹp tay dưới nách',
  'Underhook high.': 'Underhook cao.',
  'Underhook separation': 'Tách underhook',
  'Upper Body Isolation': 'Cô lập Thân trên',
  'Upright chest transfers pressure through hips, not arms.': 'Ngực thẳng truyền áp lực qua hông, không tay.',
  'Using only arm strength.': 'Chỉ dùng sức tay.',
  'Walk first.': 'Walk trước.',
  'Watch the secondary leg.': 'Theo dõi chân thứ hai.',
  'Weight distribution': 'Phân bố trọng lượng',
  'Win hand fight first.': 'Thắng hand fight trước.',
  'Win hands, align elbow, remove slack, then squeeze with chest expansion.': 'Thắng tay, căn khuỷu, bỏ slack, rồi squeeze với expansion ngực.',
  'Win wrist, slide under jaw.': 'Thắng cổ tay, trượt dưới hàm.',
  'Wrist Clamp': 'Kẹp Cổ tay',
  'Wrist across face.': 'Cổ tay qua mặt.',
  'Wrist blade is deep.': 'Sống cổ tay sâu.',
  'Wrist control': 'Wrist control',
  'Wrist control.': 'Wrist control.',
  'Wrist control keeps the shoulder lever connected.': 'Wrist control giữ lever vai kết nối.',
  'Wrist first.': 'Cổ tay trước.',
  'Wrist high.': 'Cổ tay cao.',
  'Wrist pin': 'Pin cổ tay',
  'Wrist stays pinned.': 'Cổ tay giữ pin.',
  'Wrist under chin.': 'Cổ tay dưới cằm.',
  'Wrist under chin, elbow to ribs, high elbow rotation or hip angle.': 'Cổ tay dưới cằm, khuỷu vào sườn, xoay khuỷu cao hoặc góc hông.',

  // === Right-side examples ===
  'Right-side example: right knee near head, left leg controls chest/head line.': 'Ví dụ bên phải: gối phải gần đầu, chân trái kiểm soát chest/head line.',
  'Right-side example: right leg across neck, angle toward trapped left arm.': 'Ví dụ bên phải: chân phải qua cổ, góc về tay trái bị kẹp.',
  'Right-side example: right leg clamps defender left shoulder.': 'Ví dụ bên phải: chân phải kẹp vai trái defender.',

  // === Remaining coaching cues ===
  'Angle cut.': 'Góc cắt.',
  'Angle is cut and foot is hidden.': 'Góc cắt và chân giấu.',
  'Arm across.': 'Tay qua.',
  'Arm is across and head is pinning elbow.': 'Tay qua và đầu pin khuỷu.',
  'Arm across centerline.': 'Tay qua centerline.',
  'Base first.': 'Nền trước.',
  'Body is at 90 degrees to opponent.': 'Thân vuông góc 90° với đối thủ.',
  'Branch early.': 'Branch sớm.',
  'Branch, do not force.': 'Branch, không ép.',
  'Break the connection.': 'Phá vỡ kết nối.',
  'Bridge into neck.': 'Bridge vào cổ.',
  'Chest expansion': 'Expansion ngực',
  'Chest follows their upper back.': 'Ngực theo lưng trên.',
  'Chin line angle': 'Góc đường cằm',
  'Chin line cleared and hand fight won.': 'Đường cằm thoáng và thắng hand fight.',
  'Chin strap clamp': 'Kẹp chin strap',
  'Choking elbow clamp': 'Kẹp khuỷu choke',
  'Clamp knee line.': 'Kẹp đường gối.',
  'Clamp shoulder.': 'Kẹp vai.',
  'Clamp the shoulder line.': 'Kẹp đường vai.',
  'Clear the hook.': 'Thoát hook.',
  'Close elbow.': 'Khép khuỷu.',
  'Close neck gap.': 'Đóng khe cổ.',
  'Close space inward.': 'Đóng khoảng vào trong.',
  'Close the gap.': 'Đóng khe hở.',
  'Clamp the shoulder line.': 'Kẹp đường vai.',
  'Control the hand.': 'Kiểm soát tay.',
  'Create angle.': 'Tạo góc.',
  'Crossface pressure': 'Áp lực crossface',
  'Cut angle.': 'Cắt góc.',
  'Cut the angle.': 'Cắt góc.',
  'Deep pocket.': 'Pocket sâu.',
  'Deep shin.': 'Shin sâu.',
  'Defender hides shoulder or rolls early.': 'Defender giấu vai hoặc roll sớm.',
  'Defender rolls or squares hips.': 'Defender roll hoặc xoay hông vuông.',
  'Defender stands tall.': 'Defender đứng cao.',
  'Defensive hand blocks full lock.': 'Tay phòng thủ chặn khóa đầy đủ.',
  'Diagonal post.': 'Post chéo.',
  'Direct torque to knee ligaments.': 'Torque trực tiếp vào dây chằng gối.',
  'Dismount to the side and lower hips before squeezing.': 'Xuống một bên và hạ hông trước squeeze.',
  'Ear glued.': 'Tai dính.',
  'Ear to ear.': 'Tai kề tai.',
  'Ear to head.': 'Tai kề đầu.',
  'Elbow closes ribs': 'Khuỷu khép sườn',
  'Elbow flares out.': 'Khuỷu mở ra.',
  'Elbow glued to ribs.': 'Khuỷu dính sườn.',
  'Elbow is above hip line.': 'Khuỷu trên đường hông.',
  'Elbow is centered under chin.': 'Khuỷu giữa dưới cằm.',
  'Elbow off ribs': 'Khuỷu khỏi sườn',
  'Elbow off ribs.': 'Khuỷu khỏi sườn.',
  'Elbow outside.': 'Khuỷu ngoài.',
  'Elbow too shallow.': 'Khuỷu quá nông.',
  'Elbow to ribs.': 'Khuỷu vào sườn.',
  'Elbow under chin line.': 'Khuỷu dưới đường cằm.',
  'Eliminates airway space.': 'Loại bỏ không gian thở.',
  'Exit / Safety': 'Thoát / An toàn',
  'Expand chest after slack removal.': 'Expansion ngực sau khi bỏ slack.',
  'Extend gradually and keep knees pinched.': 'Duỗi từ từ và giữ gối kẹp.',
  'Extract back.': 'Rút lưng.',
  'Face away.': 'Quay mặt đi.',
  'Feet on hips': 'Chân trên hông',
  'Feet to hips.': 'Chân vào hông.',
  'Figure-four is locked and elbow is away from ribs.': 'Figure-four khóa và khuỷu khỏi sườn.',
  'Figure-four lock': 'Khóa Figure-four',
  'Figure-four tight.': 'Figure-four chặt.',
  'Finish / Branch': 'Kết thúc / Nhánh',
  'Finish / Compression': 'Kết thúc / Nén',
  'Finish / Sweep': 'Kết thúc / Quét',
  'Finish / Torque': 'Kết thúc / Torque',
  'Fixes the lever.': 'Cố định lever.',
  'Follow shoulders.': 'Theo vai.',
  'Foot / Knee Frames': 'Frame Chân / Gối',
  'Foot hidden behind knee': 'Chân giấu sau gối',
  'Foot hidden.': 'Chân giấu.',
  'Foot is locked under armpit.': 'Chân khóa dưới nách.',
  'Forearm on ankle line, elbow closed, knees clamp, hips extend slowly.': 'Forearm trên ankle line, khuỷu khép, gối kẹp, hông duỗi chậm.',
  'Frame the shoulder.': 'Frame vai.',
  'Frames up.': 'Frame lên.',
  'Free Knee Line': 'Giải phóng Đường gối',
  'Free knee.': 'Gối tự do.',
  'Gap behind neck.': 'Khe sau cổ.',
  'Glue to back.': 'Dính vào lưng.',
  'Grapevine feet.': 'Grapevine chân.',
  'Grapevine legs': 'Grapevine chân',
  'Grip slips.': 'Grip trượt.',
  'Hand blocks far hip': 'Tay chặn hông xa',
  'Hand frames': 'Frame tay',
  'Hand moves past the shoulder line.': 'Tay qua khỏi đường vai.',
  'Hand owns wrist': 'Tay giữ cổ tay',
  'Hands base out': 'Tay base ra',
  'Hands break posture': 'Tay phá posture',
  'Hands low.': 'Tay thấp.',
  'Hands own wrist': 'Tay giữ cổ tay',
  'Hands up.': 'Tay lên.',
  'Head beside': 'Đầu cạnh',
  'Head clamp': 'Kẹp đầu',
  'Head clamp and chest-to-back.': 'Kẹp đầu và chest-to-back.',
  'Head clamp pressure': 'Áp lực kẹp đầu',
  'Head down.': 'Đầu xuống.',
  'Head floats outside.': 'Đầu nổi ra ngoài.',
  'Head glued.': 'Đầu dính.',
  'Head off center.': 'Đầu lệch tâm.',
  'Head offset': 'Đầu lệch',
  'Head too high.': 'Đầu quá cao.',
  'Head up posture': 'Đầu lên posture',
  'Head up.': 'Đầu lên.',
  'Head clamp and chest-to-back.': 'Kẹp đầu và chest-to-back.',
  'Heavy hips.': 'Hông nặng.',
  'Heel Exposure': 'Lộ Gót',
  'Heel first.': 'Gót trước.',
  'Heel in elbow pocket': 'Gót trong pocket khuỷu',
  'Heels in.': 'Gót vào.',
  'Hidden foot keeps the triangle closed without ankle exposure.': 'Chân giấu giữ triangle đóng không lộ ankle.',
  'Hide heel': 'Giấu gót',
  'Hide heel.': 'Giấu gót.',
  'Hide heel, isolate knee line, apply slow rotational torque using upper body.': 'Giấu gót, cô lập đường gối, torque xoay chậm bằng thân trên.',
  'Hide the foot.': 'Giấu chân.',
  'High mount.': 'High mount.',
  'Hip & Hook Control': 'Kiểm soát Hông & Hook',
  'Hip angle removes the roll path and sets shoulder pressure.': 'Góc hông loại bỏ đường roll và tạo áp lực vai.',
  'Hip angle to trapped arm': 'Góc hông vào tay bị kẹp',
  'Hip Angle': 'Góc Hông',
  'Hip Control': 'Kiểm soát Hông',
  'Hip Escape / Gap': 'Hip Escape / Khe hở',
  'Hip Stability': 'Ổn định Hông',
  'Hip angle': 'Góc hông',
  'Hip drive.': 'Hông đẩy.',
  'Hip escape.': 'Hip escape.',
  'Hip extension': 'Extension hông',
  'Hip out.': 'Hông ra.',
  'Hip rotates shoulder': 'Hông xoay vai',
  'Hip rotation / Angle': 'Xoay hông / Góc',
  'Hip rotation torque': 'Torque xoay hông',
  'Hip shift outside': 'Xoay hông ra ngoài',
  'Hip, not arm.': 'Hông, không tay.',
  'Hooks on thighs': 'Hook trên đùi',
  'Hooks pull.': 'Hook kéo.',
  'Isolates the heel lever.': 'Cô lập lever gót.',
  'Isolation & Finish': 'Cô lập & Kết thúc',
  'Isolation / Alignment': 'Cô lập / Căn chỉnh',
  'Isolation / Pinch': 'Cô lập / Kẹp',
  'Isolation / Posture': 'Cô lập / Posture',
  'Isolation / Ride': 'Cô lập / Ride',
  'Jerking the back.': 'Giật lưng.',
  'Keep distance.': 'Giữ khoảng cách.',
  'Keep mount.': 'Giữ mount.',
  'Keep pressure.': 'Giữ áp lực.',
  'Keep shoulders off mat.': 'Giữ vai khỏi thảm.',
  'Keep wrist blade under jaw, head glued, and finish without chasing full figure-four.': 'Giữ sống cổ tay dưới hàm, đầu dính, và finish không chase full figure-four.',
  'Kill bridge.': 'Triệt bridge.',
  'Kill hook first.': 'Triệt hook trước.',
  'Kill rotation.': 'Triệt xoay.',
  'Knee blocks hip': 'Gối chặn hông',
  'Knee clear': 'Gối thoát',
  'Knee in.': 'Gối vào.',
  'Knee kills hook': 'Gối triệt hook',
  'Knee line': 'Đường gối',
  'Knee line clamp': 'Kẹp đường gối',
  'Knee line first': 'Đường gối trước',
  'Knee line first.': 'Đường gối trước.',
  'Knee line is isolated and heel is in pocket.': 'Đường gối bị cô lập và gót trong pocket.',
  'Knee Line Control': 'Kiểm soát Đường gối',
  'Knee near ear.': 'Gối gần tai.',
  'Knee shearing pressure': 'Áp lực cắt gối',
  'Knee tight.': 'Gối chặt.',
  'Knee to hip.': 'Gối vào hông.',
  'Knees close shoulder line': 'Gối khép đường vai',
  'Knees close.': 'Gối khép.',
  'Knees finish the strangle; arms only maintain posture.': 'Gối kết thúc strangle; tay chỉ giữ posture.',
  'Knees in.': 'Gối vào.',
  'Knees pinch elbow line': 'Gối kẹp đường khuỷu',
  'Knees pinch neck': 'Gối kẹp cổ',
  'Knees pinch.': 'Gối kẹp.',
  'Knees to armpits.': 'Gối vào nách.',
  'Knees together': 'Gối khép',
  'Knees together finish': 'Kết thúc gối khép',
  'Knees together.': 'Gối khép.',
  'Knees, not neck pull.': 'Gối, không kéo cổ.',
  'Leg Extraction': 'Rút Chân',
  'Leg heavy.': 'Chân nặng.',
  'Leg over shoulder': 'Chân qua vai',
  'Lock behind head.': 'Khóa sau đầu.',
  'Lock deep.': 'Khóa sâu.',
  'Lock hips.': 'Khóa hông.',
  'Lock tight.': 'Khóa chặt.',
  'Locking': 'Khóa',
  'Locking / Angle': 'Khóa / Góc',
  'Locking the loop': 'Khóa vòng',
  'Locks head position.': 'Khóa vị trí đầu.',
  'Look into the ear.': 'Nhìn vào tai.',
  'Low hip lock': 'Khóa hông thấp',
  'Lower hips.': 'Hạ hông.',
  'Mount first.': 'Mount trước.',
  'Mount hip clamp': 'Kẹp hông mount',
  'Move hips outside before pressure.': 'Di chuyển hông ra trước áp lực.',
  'Near knee shield': 'Knee shield gần',
  'Neck line': 'Đường cổ',
  'No arm escape.': 'Không thoát tay.',
  'No blind spin': 'Không spin mù',
  'No blind spin.': 'Không spin mù.',
  'No elbow space.': 'Không khoảng khuỷu.',
  'No gap.': 'Không khe hở.',
  'No knee escape.': 'Không thoát gối.',
  'No space means no escape.': 'Không khoảng trống = không thoát.',
  'No space means no rotation.': 'Không khoảng trống = không xoay.',
  'No space.': 'Không khoảng trống.',
  'No turn in.': 'Không quay vào.',
  'Offset head.': 'Lệch đầu.',
  'One shoulder in and one shoulder out creates the strangle frame.': 'Một vai trong một vai ngoài tạo frame strangle.',
  'One shoulder out.': 'Một vai ngoài.',
  'Opponent face turns red/purple.': 'Mặt đối thủ đỏ/tím.',
  'Own wrist.': 'Giữ cổ tay.',
  'Pass Stabilization': 'Ổn định Pass',
  'Peel hands.': 'Peel tay.',
  'Peel wrist.': 'Peel cổ tay.',
  'Pin Stabilization': 'Ổn định Pin',
  'Pin head inward to stop turn-in.': 'Pin đầu vào trong để chặn turn-in.',
  'Pin the shoulder.': 'Pin vai.',
  'Pin wrist, separate elbow, rotate hips instead of arms for the finish.': 'Pin cổ tay, tách khuỷu, xoay hông thay vì tay cho finish.',
  'Pin, then release.': 'Pin, rồi thả.',
  'Pinch the neck.': 'Kẹp cổ.',
  'Pinch, then lift.': 'Kẹp, rồi nâng.',
  'Pinched knees stop shoulder rotation and make less force necessary.': 'Gối kẹp chặn xoay vai và cần ít lực hơn.',
  'Post the foot.': 'Post chân.',
  'Post wide.': 'Post rộng.',
  'Posture Break': 'Phá Posture',
  'Posture first.': 'Posture trước.',
  'Posture is broken and shoulder split is clear.': 'Posture gãy và tách vai rõ.',
  'Posture returns or stack begins.': 'Posture về hoặc stack bắt đầu.',
  'Posture tall.': 'Posture cao.',
  'Posture trapped.': 'Posture kẹt.',
  'Prevents back escape.': 'Ngăn thoát lưng.',
  'Prevents counter-hook.': 'Ngăn counter-hook.',
  'Prevents face squeeze.': 'Ngăn squeeze mặt.',
  'Prevents heel slip.': 'Ngăn trượt gót.',
  'Pull elbow back, then expand chest and close shoulders.': 'Kéo khuỷu về, rồi expansion ngực và khép vai.',
  'Pull elbow.': 'Kéo khuỷu.',
  'Pull slack backward.': 'Kéo slack về sau.',
  'Pull the head down while driving knees together and lifting hips.': 'Kéo đầu xuống trong khi đưa gối vào và nâng hông.',
  'Pulling only the head without hip lift.': 'Chỉ kéo đầu không nâng hông.',
  'Re-guard / Stabilization': 'Re-guard / Ổn định',
  'Recognize': 'Nhận diện',
  'Recovery / Stance': 'Hồi phục / Tư thế',
  'Release after pin': 'Thả sau pin',
  'Release on tap.': 'Thả khi tap.',
  'Removes neck slack.': 'Xóa slack cổ.',
  'Rib-to-wrist finish': 'Finish sườn-cổ tay',
  'Ribs to wrist.': 'Sườn vào cổ tay.',
  'Risk of fast pop.': 'Nguy cơ pop nhanh.',
  'Risk of neck crank.': 'Nguy cơ crank cổ.',
  'Rotate your entire upper body toward their toes, not just your arms.': 'Xoay toàn bộ thân trên về phía ngón chân họ, không chỉ tay.',
  'Rotate your hips and shoulders to move their hand toward their back.': 'Xoay hông và vai để đưa tay họ về lưng.',
  'Rotational body torque': 'Torque xoay thân',
  'Safe release': 'Thả an toàn',
  'Safe side.': 'Phe an toàn.',
  'Safe turning angle': 'Góc xoay an toàn',
  'Second leg.': 'Chân thứ hai.',
  'Second leg controls posture': 'Chân thứ hai kiểm soát posture',
  'Separate elbow.': 'Tách khuỷu.',
  'Shield the chest.': 'Shield ngực.',
  'Shift out.': 'Xoay ra.',
  'Shin across neck': 'Shin qua cổ',
  'Shin across.': 'Shin qua.',
  'Shin clamps shoulder': 'Shin kẹp vai',
  'Shin horizontal.': 'Shin ngang.',
  'Shin over shoulder.': 'Shin qua vai.',
  'Short choke branch': 'Nhánh choke ngắn',
  'Shoulder Clamp': 'Kẹp Vai',
  'Shoulder Control': 'Kiểm soát Vai',
  'Shoulder and wrist are trapped.': 'Vai và cổ tay kẹt.',
  'Shoulder isolation': 'Cô lập vai',
  'Shoulder isolation turns guard into a lever instead of a scramble.': 'Cô lập vai biến guard thành lever thay vì scramble.',
  'Shoulder line': 'Đường vai',
  'Shoulder line clamp': 'Kẹp đường vai',
  'Shoulder line denial': 'Chặn đường vai',
  'Shoulder split.': 'Tách vai.',
  'Shoulder trapped.': 'Vai kẹt.',
  'Shoulder-head clamp': 'Kẹp vai-đầu',
  'Shoulder-neck clamp': 'Kẹp vai-cổ',
  'Shoulders to mat.': 'Vai xuống thảm.',
  'Shrimp away': 'Shrimp ra',
  'Shrimp first.': 'Shrimp trước.',
  'Sit tall after angle.': 'Ngồi cao sau góc.',
  'Slack out.': 'Hết slack.',
  'Slack, then chest.': 'Slack, rồi ngực.',
  'Slack, then squeeze.': 'Slack, rồi squeeze.',
  'Sliding too high.': 'Trượt quá cao.',
  'Slow arch.': 'Arch chậm.',
  'Slow finish.': 'Kết thúc chậm.',
  'Slow hip extension': 'Extension hông chậm',
  'Slow hips.': 'Hông chậm.',
  'Slow pressure.': 'Áp lực chậm.',
  'Slow rotation.': 'Xoay chậm.',
  'Slow shoulder pressure': 'Áp lực vai chậm',
  'Space under neck.': 'Khoảng dưới cổ.',
  'Spinning without control.': 'Spin không kiểm soát.',
  'Square angle or foot exposed.': 'Góc vuông hoặc chân lộ.',
  'Squeeze hard.': 'Squeeze mạnh.',
  'Squeeze knees after angle, branch if posture returns.': 'Squeeze gối sau góc, branch nếu posture về.',
  'Squeeze knees.': 'Squeeze gối.',
  'Squeezing from mount.': 'Squeeze từ mount.',
  'Squeezing jaw or face.': 'Squeeze hàm hoặc mặt.',
  'Stabilization': 'Ổn định',
  'Stay heavy.': 'Giữ nặng.',
  'Stay in base.': 'Giữ base.',
  'Stay mobile.': 'Giữ di chuyển.',
  'Stiff arms.': 'Tay cứng.',
  'Stop first.': 'Dừng trước.',
  'Stops roll escape.': 'Chặn roll thoát.',
  'Strangle closes with small squeeze.': 'Strangle đóng với squeeze nhỏ.',
  'Support hand wins wrist': 'Tay support thắng cổ tay',
  'Tap comes before force spikes.': 'Tap đến trước khi lực tăng mạnh.',
  'Tap means stop.': 'Tap = dừng.',
  'Tap or sweep appears.': 'Tap hoặc sweep xuất hiện.',
  'The angle lines the thigh with the neck and removes shoulder space.': 'Góc đưa đùi vào cổ và loại bỏ khoảng vai.',
  'They stack or rotate thumb down.': 'Họ stack hoặc xoay ngón cái xuống.',
  'Thumb direction reveals the elbow line and stops rotation escape.': 'Hướng ngón cái lộ đường khuỷu và chặn thoát xoay.',
  'Thumb line.': 'Đường ngón cái.',
  'Thumb up before hips.': 'Ngón cái lên trước hông.',
  'Toe to ceiling.': 'Ngón chân lên trần.',
  'Torque slow.': 'Torque chậm.',
  'Trap the hand.': 'Kẹp tay.',
  'Trap the shoulder before sitting up.': 'Kẹp vai trước khi ngồi lên.',
  'Traps carotid.': 'Kẹp động mạch cảnh.',
  'Triangle: one shoulder in, one shoulder out, posture broken, angle cut before squeeze.': 'Triangle: một vai trong, một vai ngoài, posture gãy, góc cắt trước squeeze.',
  'Triangle is locked and angle is cut.': 'Triangle khóa và góc cắt.',
  'Triangle tight.': 'Triangle chặt.',
  'Turn away from the free leg.': 'Xoay khỏi chân tự do.',
  'Turning into their base.': 'Xoay vào base họ.',
  'Under-arm hand trap': 'Kẹp tay dưới nách',
  'Underhook high.': 'Underhook cao.',
  'Underhook separation': 'Tách underhook',
  'Upper Body Isolation': 'Cô lập Thân trên',
  'Upright chest transfers pressure through hips, not arms.': 'Ngực thẳng truyền áp lực qua hông, không tay.',
  'Using only arm strength.': 'Chỉ dùng sức tay.',
  'Walk first.': 'Walk trước.',
  'Watch the secondary leg.': 'Theo dõi chân thứ hai.',
  'Weight distribution': 'Phân bố trọng lượng',
  'Win hand fight first.': 'Thắng hand fight trước.',
  'Win hands, align elbow, remove slack, then squeeze with chest expansion.': 'Thắng tay, căn khuỷu, bỏ slack, rồi squeeze với expansion ngực.',
  'Win wrist, slide under jaw.': 'Thắng cổ tay, trượt dưới hàm.',
  'Wrist Clamp': 'Kẹp Cổ tay',
  'Wrist across face.': 'Cổ tay qua mặt.',
  'Wrist blade is deep.': 'Sống cổ tay sâu.',
  'Wrist control': 'Wrist control',
  'Wrist control.': 'Wrist control.',
  'Wrist control keeps the shoulder lever connected.': 'Wrist control giữ lever vai kết nối.',
  'Wrist first.': 'Cổ tay trước.',
  'Wrist high.': 'Cổ tay cao.',
  'Wrist pin': 'Pin cổ tay',
  'Wrist stays pinned.': 'Cổ tay giữ pin.',
  'Wrist under chin.': 'Cổ tay dưới cằm.',
  'Wrist under chin, elbow to ribs, high elbow rotation or hip angle.': 'Cổ tay dưới cằm, khuỷu vào sườn, xoay khuỷu cao hoặc góc hông.',
}

// Apply replacements
let replacedCount = 0
const seen = new Set()

for (const [en, vi] of Object.entries(mapping)) {
  if (en === vi) continue // skip no-change entries
  
  // Escape special regex characters in the English string
  const escaped = en.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')
  
  // Pattern: lt('ENGLISH', 'ENGLISH', ...) → lt('VIETNAMESE', 'ENGLISH', ...)
  // This matches the vi slot ONLY when it equals the en slot
  const regex = new RegExp(`(lt\\()('${escaped}'(?:,\\s*)('${escaped}'))`, 'g')
  
  let match
  while ((match = regex.exec(content)) !== null) {
    // Only replace if not already replaced (prevent re-replacing already translated entries)
    // The pattern ensures vi === en, so we only replace the FIRST argument
    const fullMatch = match[0]
    const replacement = `lt('${vi}', ${match[2]}`
    
    // Ensure we're not replacing something already translated
    if (fullMatch.includes(`'${en}', '${en}'`)) {
      content = content.slice(0, match.index) + replacement + content.slice(match.index + fullMatch.length)
      replacedCount++
      regex.lastIndex = match.index + replacement.length // Adjust for new length
    }
  }
  
  if (replacedCount > 0) {
    seen.add(en)
  }
}

console.log(`Replaced: ${replacedCount} occurrences across ${seen.size} unique phrases`)
fs.writeFileSync(filePath, content)
console.log('Done!')
