import fs from 'fs'

const filePath = 'src/data/qualityChecklists.ts'
let content = fs.readFileSync(filePath, 'utf8')

const mapping = {
  // === Titles (check names) ===
  'Remove slack': 'Xóa slack',
  'Slack removed': 'Đã xóa slack',
  'Knees pinch': 'Kẹp gối',
  'Knees finish': 'Gối kết thúc',
  'Foot hidden': 'Giấu chân',
  'Shin over shoulder': 'Shin qua vai',
  'Shoulder split': 'Tách vai',
  'Chin tucked': 'Cằm thu',
  'Win the hands': 'Thắng tay',
  'Head safe side': 'Đầu bên an toàn',
  'Turn with plan': 'Xoay có kế hoạch',
  'Branch when blocked': 'Branch khi bị chặn',
  'Head blocks inside': 'Đầu chặn trong',
  'Hips low and angled': 'Hông thấp và chéo',
  'Outside foot shelves': 'Chân ngoài chặn',
  'Outside feet active': 'Chân ngoài sống',
  'Hip control': 'Kiểm soát hông',
  'Settle after landing': 'Ổn định sau đáp',
  'Head pressure on shoulder': 'Áp lực đầu lên vai',
  'Wrist control': 'Kiểm soát cổ tay',
  'Low hip block': 'Chặn hông thấp',
  'Stay behind the line': 'Ở sau đường',
  'Branch early': 'Branch sớm',

  // === Coaching cues (with period) ===
  'Pull first, then finish.': 'Kéo trước, rồi finish.',
  'Branch early.': 'Branch sớm.',
  'Angle first, squeeze last.': 'Góc trước, siết sau.',
  'Mount first.': 'Mount trước.',
  'Close the gap first.': 'Đóng khoảng trống trước.',
  'Knee near ear.': 'Gối gần tai.',
  'Block posture first.': 'Chặn posture trước.',
  'Read thumb before hips.': 'Đọc ngón tay trước hông.',
  'Hips to shoulder.': 'Hông lên vai.',
  'Pinch before lift.': 'Kẹp trước nhấc.',
  'Slow hips.': 'Hông chậm.',
  'One shoulder out.': 'Một vai ra ngoài.',
  'Posture first.': 'Posture trước.',
  'Angle before squeeze.': 'Góc trước siết.',
  'Foot exposed.': 'Chân lộ.',
  'Hide foot.': 'Giấu chân.',
  'Neck crank.': 'Crank cổ.',
  'Knees, not neck.': 'Gối, không cổ.',
  'Own wrist.': 'Giữ cổ tay.',
  'Hips out first.': 'Hông ra trước.',
  'Sit tall.': 'Ngồi cao.',
  'Follow the roll.': 'Theo roll.',
  'Angle first.': 'Góc trước.',
  'Clamp then move.': 'Kẹp rồi di chuyển.',
  'Branch, do not force.': 'Branch, đừng ép.',
  'Keep a low base.': 'Giữ base thấp.',
  'Slow down and reset.': 'Chậm lại và reset.',
  'Reset before panic.': 'Reset trước hoảng.',
  'Hands first.': 'Tay trước.',
  'Control the second leg.': 'Kiểm soát chân thứ hai.',
  'Tap early.': 'Tap sớm.',
  'Drop the lock lower.': 'Hạ khóa thấp hơn.',
  'Chest down first.': 'Ngực xuống trước.',
  'Hook first.': 'Hook trước.',
  'Offset the head.': 'Đặt đầu lệch.',
  'Stabilize first.': 'Ổn định trước.',
  'Head first.': 'Đầu trước.',
  'Knee through the thigh.': 'Gối qua đùi.',
  'Far hand first.': 'Tay xa trước.',
  'Foot late.': 'Chân trễ.',
  'Settle first.': 'Ổn định trước.',
  'Wake the post up.': 'Đánh thức chân trụ.',
  'Staple then move.': 'Staple rồi di chuyển.',
  'Glue the chest.': 'Dán ngực.',
  'Seatbelt first.': 'Seatbelt trước.',
  'Hooks pull.': 'Hooks kéo.',
  'Clamp the shoulder line.': 'Kẹp đường vai.',
  'Hips low.': 'Hông thấp.',
  'Head low.': 'Đầu thấp.',
  'Crossface first.': 'Crossface trước.',
  'Break the connection.': 'Phá vỡ kết nối.',
  'Block the hips.': 'Chặn hông.',
  'Frame then move.': 'Frame rồi di chuyển.',
  'Elbow in first.': 'Khuỷu vào trước.',
  'Frame then hips.': 'Frame rồi hông.',
  'Knee returns.': 'Gối về.',
  'Turn with a plan.': 'Xoay có kế hoạch.',
  'Knee to elbow.': 'Gối về khuỷu.',
  'Bridge then insert.': 'Bridge rồi chèn.',
  'Chin down.': 'Cằm xuống.',
  'Hands first.': 'Tay trước.',
  'Shoulder to mat.': 'Vai xuống thảm.',
  'Clear the hook.': 'Dọn hook.',
  'Short posture, then move.': 'Posture ngắn, rồi di chuyển.',
  'Chin down.': 'Cằm xuống.',
  'Hips under.': 'Hông dưới.',
  'Safe side.': 'Bên an toàn.',
  'Short posture.': 'Posture ngắn.',
  'Release and reset.': 'Thả và reset.',
  'Pummel inside.': 'Pummel vào trong.',
  'Head blocks the turn.': 'Đầu chặn xoay.',
  'Post up and drive.': 'Chống và đẩy.',
  'Use the near leg.': 'Dùng chân gần.',
  'Hands block the hip.': 'Tay chặn hông.',
  'Reconnect elbow-knee.': 'Nối lại khuỷu-gối.',
  'Head safe.': 'Đầu an toàn.',
  'Turn with frames.': 'Xoay với frames.',
  'Head in.': 'Đầu trong.',
  'Low hips.': 'Hông thấp.',
  'Foot active.': 'Chân sống.',
  'Far hand.': 'Tay xa.',
  'Feet active.': 'Chân sống.',
  'Tight hips.': 'Hông chặt.',
  'Pull then settle.': 'Kéo rồi ổn định.',
  'Settle now.': 'Ổn định ngay.',
  'Head heavy.': 'Đầu nặng.',
  'Hook in.': 'Hook vào.',
  'Low base.': 'Base thấp.',
  'Stay behind.': 'Ở phía sau.',
}

let count = 0

// Apply each translation: find lt('ENGLISH', 'ENGLISH', and replace with lt('VIETNAMESE', 'ENGLISH',
for (const [en, vi] of Object.entries(mapping)) {
  // Escape special regex characters
  const escaped = en.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')
  const pattern = new RegExp(`(lt\\(\\s*)(')${escaped}('\\s*,\\s*)(')${escaped}(')`, 'g')
  const matches = content.match(pattern)
  if (matches) {
    count += matches.length
  }
  content = content.replace(pattern, `$1$2${vi}$3$4${en}$5`)
}

console.log(`Applied translations: ${count} occurrences`)
fs.writeFileSync(filePath, content, 'utf8')
console.log('File written:', filePath)
